### ISSUE TITLE
请在 wiki 的编译条目上补充上对 automake 1.15 的编译环境的依赖

### ISSUE THREAD

**Issue by septs** [holmium/dnsforwarder#100]
see https://github.com/holmium/dnsforwarder/wiki/%E7%BC%96%E8%AF%91

**Comment by holmium** [comment]
抱歉，本人才疏学浅，我也不知道依赖那个版本

**Comment by spance** [comment]
目前debian ubuntu的automake stable版本是1.14，可以先装1.14，然后
```
sudo ln -s /usr/bin/automake-1.14 /usr/bin/automake-1.15
```

**Comment by septs** [comment]
如果没有automake 1.15版本锁定请降级兼容automake 1.14

**Comment by septs** [comment]
@holmium 测试automake 1.14可以编译通过
因此希望将 https://github.com/holmium/dnsforwarder/blob/5/configure#L2350 改为1.14
