### ISSUE TITLE
是否可以添加类似于allowed client的选项，只有选项内的ip或者ip段才可以返回查询记录

### ISSUE THREAD

**Issue by sunshineplan** [holmium/dnsforwarder#102]
这样的做法可以提高安全性

**Comment by holmium** [comment]
还是用防火墙吧

**Comment by sunshineplan** [comment]
嗯，用防火墙也不错
iptables -I INPUT -p udp --dport 53 -j DROP
iptables -I INPUT -s 10.8.8.0/24 -p udp --dport 53 -j ACCEPT
