### ISSUE TITLE
提个个建议，LocalInterface 修改为0.0.0.0能不能实现监听本机任意IP

### ISSUE THREAD

**Issue by lsnmx** [holmium/dnsforwarder#103]
LocalInterface 为局域网IP时，快捷方式放到WIN8.1 X64启动项 "D:\Program Files (x86)\DNSForwarder\DNSForwarder_X64.exe" -d 下重启PC不会自动启动了，修改为127.0.0.1就正常了，大神能不能修复一下，提个个建议，LocalInterface 修改为0.0.0.0能不能实现监听本机任意IP

**Comment by holmium** [comment]
你先告诉我哪个IP是任意IP

**Comment by nxtreaming** [comment]
他的意思应该只本地机器上的多个网卡的IP，如果是，则可以。

**Comment by lsnmx** [comment]
我意思是 LocalInterface 0.0.0.0 而不是现在要固定本机IP比如192.168.1.88，写到LocalInterface 192.168.1.88局域网解析才生效，这样好麻烦呀，希望能监听到本机IP，局域网使用dnsforwarder做为服务器时就不用它么麻烦！大神能不能实现啊

**Comment by tofuliang** [comment]
一直可以吧,我在路由器上跑dnsforwarder,就是监听 0.0.0.0:53的,所以设备都是用dnsforwarder的.

lsnmx <notifications@github.com>于2015年8月11日周二 下午9:24写道：

**Comment by lsnmx** [comment]
# tofuliang  你家路由真牛能跑X86啊，给点个设置参考一下，谢谢

**Comment by tofuliang** [comment]
不是x86,是mips,,,,,,,  有源码,自己编就是了... 至于配置,就是 LocalInterface 0.0.0.0

lsnmx <notifications@github.com>于2015年8月12日周三 下午2:57写道：

**Comment by lsnmx** [comment]
# tofuliang 怎么我在X64上的dnsforwarder ，不能实现，

**Comment by holmium** [comment]
> In the context of servers, 0.0.0.0 means "all IPv4 addresses on the local machine". If a host has two ip addresses, 192.168.1.1 and 10.1.2.1, and a server running on the host listens on 0.0.0.0, it will be reachable at both of those IPs.

https://en.wikipedia.org/wiki/0.0.0.0

所以LZ的问题应该是，在程序启动的时候，局域网还没有完全就绪，尤其可能IP地址还没有获取到（如果是动态获取的）

**Comment by huxim** [comment]
我也觉得加上这个支持比较好,主要是配置文件不用改来改去的
