### ISSUE TITLE
UDPFilter和DedicatedServer发生冲突

### ISSUE THREAD

**Issue by wstchql** [holmium/dnsforwarder#106]
配置文件：
UDPServer 114.114.115.115,223.6.6.6,180.76.76.76
DedicatedServer *.g.cn 223.6.6.6,g.cn 223.6.6.6
ParallelQuery true
UDPFilter true
ExcludedDomain中没有g.cn，也就是说g.cn使用udp向上游查询
输出结果：
dig g.cn @127.0.0.1

; <<>> DiG 9.10-P2 <<>> g.cn @127.0.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached
窗口输出：
Aug 29 21:30:39 [B][g.cn] False package, discarded :
   IPv4 Address:203.208.41.145
   IPv4 Address:203.208.41.144
   IPv4 Address:203.208.41.146
   IPv4 Address:203.208.41.147
   IPv4 Address:203.208.41.148
Aug 29 21:30:55 [U][127.0.0.1][IPv4 Address][g.cn] Timed out.
结果分析：
g.cn使用udp向固定的上游223.6.6.6查询；
223.6.6.6服务器响应性较好，极快的返回正确结果 IPv4 Address:203.208.41.145；
但由于开启了UDPFilter，被当做欺骗包丢弃；
又由于指定了DedicatedServer，所以最后查询无输出。
希望可以解决这个冲突，最好是使UDPFilter对DedicatedServer项目不起作用。
谢谢！

**Comment by holmium** [comment]
UDPAntiPollution 功能早已失效

**Comment by wstchql** [comment]
你的意思是延时丢弃udp返回包的方法已失效？
那我可以关闭UDPAntiPollution 了。
另外，推荐一下openwrt上的Chinadns的过滤方法，不太明白原理。
可以看下能移植不。。。

**Comment by matrixirtam** [comment]
最新版本去除了GFW list不知为何？
