### ISSUE TITLE
windows 10下程序停止工作

### ISSUE THREAD

**Issue by yyysuo** [holmium/dnsforwarder#108]
不管是chrome浏览器下载文件还是QQ传输文件，都会导致dnsforwarder停止工作。

**Comment by Chu2koi** [comment]
我也是用windows10，不过没这情况，一切正常

**Comment by wstchql** [comment]
有类似问题，最新版win10下，经常出现CPU占用50%的状况，已用回15版本，一切正常。

**Comment by yyysuo** [comment]
![Uploading 2015-09-11_23-13-38.png…]()
补一个报错的图
