### ISSUE TITLE
最近出现很多错误

### ISSUE THREAD

**Issue by huxim** [holmium/dnsforwarder#112]
An error occured while receiving from 127.0.0.1 : 10054 : An existing connection was forcibly closed by the remote host.

大量出现,使用udp查询也会有这个错误,更奇怪的是输出的日志文件中没有,只能在命令行中看到

**Comment by xieqiyou** [comment]
我这也很多。系统是win10的楼上是啥系统啊

**Comment by huxim** [comment]
win10

**Comment by xieqiyou** [comment]
不知道怎么折腾的。
我的被我折腾好了。你试试配置里面把53端口改成其他的，运行下，再改回来试试
