### ISSUE TITLE
小白被mac下编译难住了，无奈网上的那些东西都看不懂

### ISSUE THREAD

**Issue by ych5318** [holmium/dnsforwarder#113]
我把dnsforwarder -5文件夹放在了 ~/ 目录 已经安装了Xcode 执行了./configure
出现
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for log in -lm... yes
checking for sqrt in -lm... yes
checking for curl_global_init in -lcurl... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking wordexp.h usability... yes
checking wordexp.h presence... yes
checking for wordexp.h... yes
checking for curl/curl.h... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for setenv... yes
checking for wordexp... yes
checking for pid_t... (cached) yes
checking for size_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
然后就不知道怎么弄了
从没用过UNIX Linux。。。

**Comment by holmium** [comment]
我也不会

**Comment by ych5318** [comment]
= = 。。。不要这么果断~

**Comment by ych5318** [comment]
学习了点知识后
sudo dnsforwarder -p
mkdir : /var/root/.dnsforwarder failed : File exists
Please put configure file into `/var/root/.dnsforwarder' and rename it to `config'.

sudo ls /var/root/.dnsforwarder/
config
确实有config这个文件啊 
我是把win中的dnsforwarder.config改的名字

**Comment by holmium** [comment]
那直接运行会有什么问题吗？

**Comment by ych5318** [comment]
看了别人说的必须自己编译。。。原来可以直接运行
非常感谢作者回复！
