### ISSUE TITLE
OverrideTTL 选项无效

### ISSUE THREAD

**Issue by QuChao** [holmium/dnsforwarder#114]
配置如下：
```
UseCache true
MemoryCache true

OverrideTTL 3600
```

期望覆盖写 TTL 值，
但 `dig` 到的仍旧是原始值。

版本 v5.0.18 。谢谢。

**Comment by holmium** [comment]
抽时间看看

**Comment by holmium** [comment]
这个只是控制缓存，没有缓存的条目是不会被Overrided的

**Comment by QuChao** [comment]
确实没有任何 CacheControl 条目，
想请教下如何确认目标域名是否有被程序缓存呢？
Thx
