### ISSUE TITLE
使用nslookup会timed out

### ISSUE THREAD

**Issue by huxim** [holmium/dnsforwarder#116]
C:\Users\huxim>nslookup www.twitter.com 127.0.0.1
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    twitter.com
Addresses:  199.16.158.179
          199.16.158.168
Aliases:  www.twitter.com

**Comment by holmium** [comment]
那是因为1.0.0.172.in-addr.arpa确实没结果

**Comment by huxim** [comment]
使用dnsforwarder之后电脑网络图标就有黄色叹号了,不知道windows的ncsi是不是用的nslookup命令,如果是的话超时结果会导致判定为网络不通么?

C:\Users\huxim>nslookup dns.msftncsi.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    dns.msftncsi.com
Addresses:  fd3e:4f5a:5b81::1
          131.107.255.255


C:\Users\huxim>nslookup www.msftncsi.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    a1961.dspg2.akamai.net
Addresses:  42.99.254.138
          42.99.254.162
Aliases:  www.msftncsi.com
          www.msftncsi.com.edgesuite.net
