### ISSUE TITLE
11月22日windows 32位这个版本使用时候报错

### ISSUE THREAD

**Issue by playnetcn** [holmium/dnsforwarder#121]
我电脑是windows 7 32位，使用上一版本没有问题，但是22日这版，日志报错，打不开页面
错误日志如下：
Nov 22 20:38:47 [B][site.baidu.com] False package, discarded :
   Canonical Name:cn.hao123.n.shifen.com
   IPv4 Address:180.149.132.3
Nov 22 20:38:47 [B][www.hao123.com] False package, discarded :
   Canonical Name:hao123.n.shifen.com
   IPv4 Address:123.125.114.5
   IPv4 Address:61.135.162.10
Nov 22 20:38:47 [B][www.hao123.com] False package, discarded :
   Canonical Name:hao123.n.shifen.com
   IPv4 Address:61.135.162.10
   IPv4 Address:123.125.114.5
Nov 22 20:38:47 [B][dlresctrl.phub.sandai.net] False package, discarded
   Canonical Name:t33085.sandai.net
   IPv4 Address:180.97.151.86
Nov 22 20:38:47 [B][hubstat.sandai.net] False package, discarded :
   Canonical Name:telhubstat.sandai.net
   IPv4 Address:58.61.39.130
   IPv4 Address:58.61.39.234
Nov 22 20:38:47 [B][dlresctrl.phub.sandai.net] False package, discarded
   Canonical Name:t33085.sandai.net
   IPv4 Address:180.97.151.86
Nov 22 20:38:47 [B][imhub5pr.sandai.net] False package, discarded :
   IPv4 Address:58.254.134.249
   IPv4 Address:58.254.134.209
   IPv4 Address:58.254.134.218
   IPv4 Address:58.254.134.237
Nov 22 20:38:47 [B][hub5pr.sandai.net] False package, discarded :
   Canonical Name:cnchub5pr.sandai.net
   IPv4 Address:58.254.134.238
   IPv4 Address:58.254.134.136
   IPv4 Address:58.254.134.204
   IPv4 Address:58.254.134.150
   IPv4 Address:58.254.134.138
   IPv4 Address:58.254.134.137
   IPv4 Address:58.254.134.233
   IPv4 Address:58.254.134.139
Nov 22 20:38:47 [B][hub5pr.sandai.net] False package, discarded :
   Canonical Name:cnchub5pr.sandai.net
   IPv4 Address:58.254.134.204
   IPv4 Address:58.254.134.136
   IPv4 Address:58.254.134.138
   IPv4 Address:58.254.134.233
   IPv4 Address:58.254.134.137
   IPv4 Address:58.254.134.139
   IPv4 Address:58.254.134.238
   IPv4 Address:58.254.134.150
Nov 22 20:38:47 [B][imhub5pr.sandai.net] False package, discarded :
   IPv4 Address:58.254.134.249
   IPv4 Address:58.254.134.237
   IPv4 Address:58.254.134.209
   IPv4 Address:58.254.134.218
Nov 22 20:38:47 [B][imhub5pr.sandai.net] False package, discarded :
   IPv4 Address:58.254.134.218
   IPv4 Address:58.254.134.249
   IPv4 Address:58.254.134.237
   IPv4 Address:58.254.134.209
Nov 22 20:38:47 [B][hub5pr.sandai.net] False package, discarded :
   Canonical Name:cnchub5pr.sandai.net
   IPv4 Address:58.254.134.138
   IPv4 Address:58.254.134.139
   IPv4 Address:58.254.134.233
   IPv4 Address:58.254.134.150
   IPv4 Address:58.254.134.136
   IPv4 Address:58.254.134.238
   IPv4 Address:58.254.134.204
   IPv4 Address:58.254.134.137
Nov 22 20:38:47 [B][hubstat.sandai.net] False package, discarded :
   Canonical Name:telhubstat.sandai.net
   IPv4 Address:58.61.39.234
   IPv4 Address:58.61.39.130
Nov 22 20:38:47 [B][imhub5pr.sandai.net] False package, discarded :
   IPv4 Address:58.254.134.209
   IPv4 Address:58.254.134.237
   IPv4 Address:58.254.134.249
   IPv4 Address:58.254.134.218
Nov 22 20:38:47 [B][s0.hao123img.com] False package, discarded :
   Canonical Name:hao123.jomodns.com
   IPv4 Address:106.38.179.49
Nov 22 20:38:47 [B][dlresctrl.phub.sandai.net] False package, discarded
   Canonical Name:c16b59.sandai.net
   IPv4 Address:122.143.5.109
Nov 22 20:38:47 [B][hubstat.sandai.net] False package, discarded :
   Canonical Name:cnchubstat.sandai.net
   IPv4 Address:123.129.242.154
   IPv4 Address:123.129.242.179
Nov 22 20:38:47 [B][hm.baidu.com] False package, discarded :
   Canonical Name:hm.e.shifen.com
   IPv4 Address:220.181.7.190
Nov 22 20:38:47 [B][hm.baidu.com] False package, discarded :
   Canonical Name:hm.e.shifen.com
   IPv4 Address:220.181.7.190
Nov 22 20:38:47 [B][hm.baidu.com] False package, discarded :
   Canonical Name:hm.e.shifen.com
   IPv4 Address:220.181.7.190
Nov 22 20:38:47 [B][hm.baidu.com] False package, discarded :
   Canonical Name:hm.e.shifen.com
   IPv4 Address:220.181.7.190
Nov 22 20:38:48 [B][tieba.baidu.com] False package, discarded :
   Canonical Name:post.n.shifen.com
   IPv4 Address:180.149.133.172
   IPv4 Address:180.149.133.174
   IPv4 Address:180.149.133.173
   IPv4 Address:180.149.144.216
Nov 22 20:38:48 [B][tieba.baidu.com] False package, discarded :
   Canonical Name:post.n.shifen.com
   IPv4 Address:180.97.104.41
   IPv4 Address:180.97.104.40
Nov 22 20:38:48 [B][tieba.baidu.com] False package, discarded :
   Canonical Name:post.n.shifen.com
   IPv4 Address:103.235.46.140
   IPv4 Address:103.235.46.141
   IPv4 Address:103.235.46.139
Nov 22 20:38:48 [B][imhub5pr.sandai.net] False package, discarded :
   IPv4 Address:121.9.209.160
   IPv4 Address:121.9.209.180

**Comment by holmium** [comment]
哦，抽时间改改，先用旧版本吧

**Comment by yyysuo** [comment]
把UDP防污染关了试试。
