### ISSUE TITLE
排除列表文件是什么格式的？GFWLIST是什么时候弃用的啊？

### ISSUE THREAD

**Issue by yyysuo** [holmium/dnsforwarder#123]
主要解析方式是UDP，次要是TCP。在排除列表内的走TCP，不在的走UDP。

之前GFWLIST生效的时候，不用关心排除列表，看最新的config文件示例，gfwlist文件竟然没有了，那就只能依靠排除列表了。

直接在config里面添加排除列表是生效了，google.com确实是通过TCP解析了，但是建立一个ELIST文本文件，在里面只写一句google.com，结果google.com走了UDP解析，那么排除列表文件的格式有什么要求呢？

**Comment by holmium** [comment]
一行一个域名

**Comment by yyysuo** [comment]
我建立了一个txt文件，就写了一行,内容是google.com 结果还是走了UDP解析了，我主协议是UDP的。

**Comment by yyysuo** [comment]
已经在config文件里面指定了排除文件路径了

**Comment by rampageX** [comment]
看下 txt 文件编码/换行符有没问题
