### ISSUE TITLE
排除列表和ALWAYS列表感觉功能重复了....

### ISSUE THREAD

**Issue by greyjojo** [holmium/dnsforwarder#124]
既然使用了排除列表，比如我主用了UDP，排除列表中的域名自然走TCP，主用了TCP，排除列表自然会走UDP，ALWAYS列表中的域名就重复了嘛......

**Comment by holmium** [comment]
改PrimaryServer时就不用来回改ExcludedDomain了

**Comment by greyjojo** [comment]
但是，很少会有改动主服务器的情况吧，按理来说不算常用功能，我建议一下排除列表就可以了......去掉“总是”功能，然后完善排除列表功能，只是建议，建议而已....

**Comment by holmium** [comment]
我就经常改
