### ISSUE TITLE
建议加入系统托盘图标

### ISSUE THREAD

**Issue by huxim** [holmium/dnsforwarder#125]
类似于
https://github.com/cyfdecyf/cow
平时在后台运行占一个任务栏位置比较浪费,而用-d参数又完全看不到输出,只能看日志比较麻烦.
另外如果托盘图标可以有重载配置功能就更好了

**Comment by holmium** [comment]
暂时不想加

**Comment by lonsx** [comment]
给你个batch将dnsforwarder添加到服务，service文件夹放在与dnsforwarder.exe同一个文件夹。
cd /d %~dp0
@echo @echo off > !register_as_server.bat
@echo sc stop Dnsforwarder >> !register_as_server.bat
@echo sc delete Dnsforwarder >> !register_as_server.bat
@echo sc create Dnsforwarder binPath= "%~dp0srvanydns.exe" start= auto >> !register_as_server.bat
@echo sc description Dnsforwarder "DNS 本地代理2 - 利用延时丢包&Tcp协议忽略GFW的DNS缓存污染。" >> !register_as_server.bat
@echo reg add HKLM\SYSTEM\CurrentControlSet\Services\Dnsforwarder\Parameters /v Application /d "%~dp0..\Dnsforwarder.exe" /f >> !register_as_server.bat
@echo reg add HKLM\SYSTEM\CurrentControlSet\Services\Dnsforwarder\Parameters /v AppDirectory /d "%~dp0.." /f >> !register_as_server.bat
@echo sc start Dnsforwarder >> !register_as_server.bat
@echo ::@echo. >> !register_as_server.bat
@echo ::@echo 安装已完成，Dnsforwarder 服务已经启动。 >> !register_as_server.bat
@echo ::@echo. >> !register_as_server.bat
@echo ::@echo 请将您宽带连接的DNS地址设为127.0.0.1。 >> !register_as_server.bat
@echo ::@echo. >> !register_as_server.bat
@echo ::@echo 然后，Enjoy it :-) >> !register_as_server.bat
@echo ::@echo. >> !register_as_server.bat
@echo @pause >> !register_as_server.bat

@echo @echo off > !delete_Dnsforwarder_server.bat
@echo sc stop Dnsforwarder >> !delete_Dnsforwarder_server.bat
@echo sc delete Dnsforwarder >> !delete_Dnsforwarder_server.bat
@echo ::@echo. >> !delete_Dnsforwarder_server.bat
@echo ::@echo 操作成功，Dnsforwarder 服务已被删除 :-) >> !delete_Dnsforwarder_server.bat
@echo ::@echo. >> !delete_Dnsforwarder_server.bat
@echo @pause >> !delete_Dnsforwarder_server.bat

@echo 安装文件已生成.
@echo.
@echo 以 *管理员身份* 运行这个文件：!register_as_server.bat 注册服务；!delete_Dnsforwarder_server.bat 删除此服务
@echo.
@pause

**Comment by lonsx** [comment]
不知道怎么上传附件，改一下后缀名为zip

[service.pdf](https://github.com/holmium/dnsforwarder/files/60362/service.pdf)
