### ISSUE TITLE
求救，用了新版后，时钟同步无法解析时钟同步服务器了

### ISSUE THREAD

**Issue by mtgitnerd** [holmium/dnsforwarder#126]
time.windows.com
time-nw.nist.gov
time.nist.gov
time-a.nist.gov
time-b.nist.gov
这些都不行了

**Comment by holmium** [comment]
贴输出

**Comment by mtgitnerd** [comment]
![image](https://cloud.githubusercontent.com/assets/15828964/11860998/9c3ff2e4-a4b6-11e5-9f4a-d8b79270cbb5.png)

**Comment by mtgitnerd** [comment]
![image](https://cloud.githubusercontent.com/assets/15828964/11861013/b53f4b46-a4b6-11e5-9d65-e944d45e671c.png)

**Comment by mtgitnerd** [comment]
![image](https://cloud.githubusercontent.com/assets/15828964/11861021/c9af81c2-a4b6-11e5-9093-d8e2fde87b49.png)

**Comment by mtgitnerd** [comment]
是我哪里没配置对么，用的默认的配置文件

**Comment by holmium** [comment]
DNS解析应该是没有问题的，可能是其它原因导致的
