### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by testcaoy7** [holmium/dnsforwarder#127]
1、能不能增加重新载入配置文件的快捷键？每次修改配置文件后都要退出程序，然后ipconfig/flushdns，再重新启动挺麻烦的。如果能加入一个快捷键，能自动清理缓存外加重载配置文件就方便了。

2、能不能增加伪造本地IP地址的功能？DNS服务器会就地理位置返回离用户计算机最近的IP，如果能够把这个功能反过来用，比如把用户电脑的IP伪造成某个来自美国的IP来查询Google的域名，也许就能获得一些在美国还没被封掉的Google IP？（类似于操纵edns-subnet）

**Comment by holmium** [comment]
第一个问题自己用快捷键加批处理或脚本可以解决
第二个懒得实现
