### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by spance** [holmium/dnsforwarder#131]
Hi,

最近频繁出现2个情况，

1、无响应---无论dig还是浏览器请求的都没有反应，console上也没有任何输出
2、偶然出现cpu 100%
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
23084 abcd      20   0  493012  16516   3632 S  99.8  0.4   9:40.13 dnsforwarder
```

另外（可能是问题1），之后就没有任何响应了，必须重启才可以
```
dig r1.ykimg.com
;; Got bad packet: bad compression pointer
187 bytes
........
```

 Version 5.0.29, Linux amd64.

**Comment by spance** [comment]
抓包看了一下，发现114返回的响应里面有循环压缩指针：
![2016-03-29_191127](https://cloud.githubusercontent.com/assets/3322424/14106246/8f8ce0f2-f5e2-11e5-8101-e39cb8463e09.png)

这个应该是个错误的报文，dig给出了错误“bad compression pointer”，希望处理一下避免这个错误报文导致dnsforwarder出错。

**Comment by holmium** [comment]
十分感谢！！
抽时间研究一下

**Comment by holmium** [comment]
这个应该已经被修复了。

**Comment by spance** [comment]
在5.0.31下测试已经不会出问题了，但是如果能把这种坏的dns回应过滤掉会更好。
