### ISSUE TITLE
现在是不是DNSTCP也被墙了?

### ISSUE THREAD

**Issue by asdyjd** [holmium/dnsforwarder#132]
用这个软件,WINDOWS下,没有配置文件,就是默认的TCP 8.8.8.8,其他网站都能解析,就是被墙的几个FACEBOOK,TWITTER,GOOGLE上不去.
这是TCP DNS也不能用了吗?

**Comment by asdyjd** [comment]
```
E:\software\project\chinaip>dig www.baidu.com

; <<>> DiG 9.10.3-P4 <<>> www.baidu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35635
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;www.baidu.com.                 IN      A

;; ANSWER SECTION:
www.baidu.com.          186     IN      CNAME   www.a.shifen.com.
www.a.shifen.com.       287     IN      A       14.215.177.38
www.a.shifen.com.       287     IN      A       14.215.177.37

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Apr 06 13:26:15 GMT 2016
;; MSG SIZE  rcvd: 104

```
```

E:\software\project\chinaip>dig www.facebook.com

; <<>> DiG 9.10.3-P4 <<>> www.facebook.com
;; global options: +cmd
;; connection timed out; no servers could be reached

```

**Comment by asdyjd** [comment]
以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   物理地址. . . . . . . . . . . . . : 00-90-F5-F8-3E-10
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::68c3:bd9a:1e7c:fdb7%5(首选)
   IPv4 地址 . . . . . . . . . . . . : 10.139.10.54(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : fe80::213:19ff:feaa:f27f%5
                                       10.139.10.1
   DHCPv6 IAID . . . . . . . . . . . : 83923189
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-1E-82-29-AF-00-0C-29-43-F0-D4
   DNS 服务器  . . . . . . . . . . . : 127.0.0.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

**Comment by holmium** [comment]
是的

**Comment by Chu2koi** [comment]
8.8.8.8的tcp被污染很久了，你需要找那些非标准端口的dns来t用才不会被污染
