### ISSUE TITLE
查询lhcatv.com域名死循环了

### ISSUE THREAD

**Issue by godwasdog** [holmium/dnsforwarder#134]
OverrideTTL 64800
 

/usr/bin/dnsforwarder -f /etc/dnsforwarder.config
DNSforwarder mainly by holmium. Version 5.0.30 . License : GPL v3.
Time of compilation : Apr 27 2016 15:46:24.

Please run `dnsforwarder -p' if something goes wrong.

Configure File : /etc/dnsforwarder.config

Local working interface:192.168.1.254
Local working port:5757
Local TCP is opened:No
Primary server:UDP
TCP Server:8.8.4.4
TCP Server:8.8.8.8
UDP Server:119.29.29.29
UDP Server:114.114.115.115
UDP Server:202.181.224.2
UDP Parallel Query:Yes
UDP Filter:No
Use cache:Yes
Memory Cache:Yes
Ignore TTL:No

[INFO] Excluded & Disabled list initialized.
[INFO] UDP socket 192.168.1.254:5757 created.
[INFO] Now you can set DNS to 192.168.1.254.
Apr 27 16:19:18 [U][192.168.1.94][IPv4 Address][lhcatv.com] : 42 bytes
   Canonical Name:lhcatv.com
Apr 27 16:19:30 [C][192.168.1.94][IPv4 Address][lhcatv.com] : 2284 bytes
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   Canonical Name:lhcatv.com
   And 60 More ...

**Comment by godwasdog** [comment]
和 paopaoku.com

**Comment by holmium** [comment]
域名本身的问题

**Comment by godwasdog** [comment]
我知道是域名问题，但是nslookup第一次没问题，第二次dnsforwarder就死了，后面就无响应了，要重启dnsforwader才行

**Comment by godwasdog** [comment]
测试dnsmasq,pdnsd是不会无响应的

**Comment by holmium** [comment]
我这里是没有问题的，有时间我看一下吧

**Comment by holmium** [comment]
好吧确实有这个问题，抽时间修复一下

**Comment by holmium** [comment]
这个BUG应该被修复了
