### ISSUE TITLE
可以在OPENWRT上使用吗?

### ISSUE THREAD

**Issue by asdyjd** [holmium/dnsforwarder#136]
希望在路由器上使用.

**Comment by godwasdog** [comment]
https://github.com/shangjiyu/openwrt-extra

**Comment by holmium** [comment]
应该可以吧，我也没试过

**Comment by godwasdog** [comment]
可以，我都编译使用了

**Comment by asdyjd** [comment]
@godwasdog 
你怎么编译的？
我把电脑上的dnsforwarder直接复制上到路由器上，不能用啊。

**Comment by godwasdog** [comment]
要在Linux上用openwrt SDK 编译
