### ISSUE TITLE
windows下不能下载HOSTS文件呀

### ISSUE THREAD

**Issue by asdyjd** [holmium/dnsforwarder#137]
配置里面:
#Hosts https://raw.githubusercontent.com/racaljk/hosts/master/hosts
Hosts https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts
上面这两个地址都试过,但是都显示如下:
D:\Program Files\dnsforwarder\codeblocks_win\bin\Release_x64>dnsforwarder.exe
DNSforwarder mainly by holmium. Version 5.0.30 . License : GPL v3.
Time of compilation : Apr  2 2016 13:29:22.

Configure File : D:\Program Files\dnsforwarder\codeblocks_win\bin\Release_x64\dnsforwarder.config

Local working interface:127.0.0.1
Local working port:53
Local TCP is opened:Yes
Primary server:TCP
TCP Server:8.8.4.4
UDP Server:202.120.224.6
UDP Server:202.120.224.26
UDP Parallel Query:No
UDP Filter:No
Hosts File:https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts
Use cache:Yes
Memory Cache:Yes
Ignore TTL:No

[INFO] Excluded & Disabled list initialized.
[INFO] Local hosts file : "D:\Program Files\dnsforwarder\codeblocks_win\bin\Release_x64\hosts.txt"
[INFO] Loading the existing hosts file ...
[INFO] Loading hosts file completed, 0 IPv4 Hosts, 0 IPv6 Hosts, 0 CName Redirections, 0 items are excluded.
[INFO] UDP socket 127.0.0.1:53 created.
[INFO] TCP socket 127.0.0.1:53 created.
[INFO] Now you can set DNS to 127.0.0.1.
[INFO] Getting hosts from https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts ...

D:\Program Files\dnsforwarder\codeblocks_win\bin\Release_x64>
就直接结束了,怎么办?

**Comment by StrollStars** [comment]
检查下“D:\Program Files\dnsforwarder\codeblocks_win\bin\Release_x64\hosts.txt”文件中是否含有“https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts”的内容，看起来没有问题。

**Comment by holmium** [comment]
下载Hosts的部分确实一直有bug，昨天刚修复，不知是否还有问题
