### ISSUE TITLE
关于排除列表问题

### ISSUE THREAD

**Issue by StrollStars** [holmium/dnsforwarder#138]
建议对排除列表的说明再详细些，在5.0.32版本下进行测试，发现如下情况：
①一级域名不支持通配符，例如google.*并不能让google.com走另一组服务器。
②相对文件路径不能添加`和'，只需要有% %包含就可以了，否则无效。
③支持#开始的注释。

**Comment by holmium** [comment]
有空看下，谢谢

**Comment by horizonl** [comment]
说起来，能吧gfwlist直接加入排除列表吗？
