### ISSUE TITLE
排除列表的路径和内容怎么写啊 格式是怎样的？

### ISSUE THREAD

**Issue by nomosaic** [holmium/dnsforwarder#140]
路径名是“file://盘符:/xxx”，“file:///盘符:/xxx”？还是“盘符:\xxx”？
相对路径怎么写？是 %PROGRAMDIRECTORY%\xxx.txt，还是 %程序所在文件夹%\xxx.txt？
排除文件列表是 每行单独一个 还是用逗号或者空格分开？ 是否支持通配符？

**Comment by StrollStars** [comment]
%PROGRAMDIRECTORY%不就是程序所在文件夹？%PROGRAMDIRECTORY%\xxx.txt是可以的。
内容格式可以看我的#138
