### ISSUE TITLE
关于机制和性能问题

### ISSUE THREAD

**Issue by StrollStars** [holmium/dnsforwarder#141]
1.解析的顺序是怎样的？是不是依次为：缓存→Hosts文件→访问DNS服务器？
2.如果Hosts文件加载过多，对性能和解析速度的影响大吗？
3.是否可以并发处理缓存、Hosts文件和访问DNS服务器，然后在提取解析结果的时候区分优先？

**Comment by holmium** [comment]
1.Hosts→缓存→DNS服务器。
2.应该不会有明显的影响。
3.目前不可以，将来也没有这个打算。

**Comment by StrollStars** [comment]
如果2不会有明显影响，那么3就没有关系，因为每个列表都是上万条的内容，所以担心延迟解析。

**Comment by holmium** [comment]
如果是大量带通配符的就会有明显的影响。

**Comment by StrollStars** [comment]
那诸如Google系列和Dropbox系列有大量域名，可以用通配符减少条目，那是用通配符好还是不用好？我本想把上万条的列表精简到几千条，如果这样的话还是保留上万条的好了？

**Comment by holmium** [comment]
通配符是用数组存的，每次需要逐条匹配。不带通配符的是用哈希表存的，每次只需要匹配少数几条即可。

**Comment by StrollStars** [comment]
那不带通配符的需要按一定规律排列吗？比如首字母

**Comment by holmium** [comment]
不需要
