### ISSUE TITLE
关于AppendHosts

### ISSUE THREAD

**Issue by StrollStars** [holmium/dnsforwarder#142]
AppendHosts支持以下功能：

> # 也可以定义指向一个 IP 列表的 Hosts 项（仅支持 IPv4 地址），例如：
#  AppendHosts <list1> www.123.com
# 此时 www.123.com 将会指向 list1 中最快的 IP 地址。

现在可否增加反过来的功能，即定义一个域名列表，指向同一个IP？

**Comment by holmium** [comment]
写多条Hosts就可以了

**Comment by StrollStars** [comment]
域名列表上万条……

**Comment by holmium** [comment]
用Excel一拖，一复制不就行了

**Comment by StrollStars** [comment]
本想把大量内容的列表外置，保证配置文件的精简和方便升级，那这样也行。

**Comment by holmium** [comment]
这样就可以了
AppendHosts 123.123.123.123 aaa
AppendHosts aaa 1.com
AppendHosts aaa 2.com
AppendHosts aaa 3.com

外部的Hosts也可以这样
123.123.123.123 aaa
aaa 1.com
aaa 2.com
aaa 3.com

**Comment by StrollStars** [comment]
结合CName，谢谢指点。
