### ISSUE TITLE
关于UDPBlock_IP

### ISSUE THREAD

**Issue by StrollStars** [holmium/dnsforwarder#143]
UDPBlock_IP默认内置了几个，是不是这几个频率比较高？
据最近观察，[ChinaDNS](https://github.com/shadowsocks/ChinaDNS)的[iplist.txt](https://github.com/shadowsocks/ChinaDNS/blob/master/iplist.txt)似乎是最全的（当然也很久没更新了），可否考虑引用？如果手动添加的话估计又得外挂列表了，还是作者觉得没必要？

可否增加功能，如果解析触发到该列表，就再次发起TCP解析？因为根据观察，发现日志中出现[B]后，网站就直接无法打开了，即使走代理也无效。
PS：感觉UDP并发或许能起加速作用，而无法起修正作用。因为内服会被劫持，外服会被污染，无法通过UDP解决。

扩展：可有办法获取解析错误的域名列表？我从一些Hosts文件提取，发现总有不足。如果根据被Black的IP效率太低了。

**Comment by holmium** [comment]
不考虑
