### ISSUE TITLE
排除列表怎么配合GFWlist使用呢？

### ISSUE THREAD

**Issue by kenneth104** [holmium/dnsforwarder#144]
现在使用Chrome+SwitchyOmega
其中配置GFWlist
`https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt`

# **现在排除列表直接填写上面的，能生效么**

由于现在用的长宽，访问国外DNS还是有点问题，本地再加了个cn2的跳板，即使这样全部走TCP访问国外DNS也失去长宽DNS反馈回来的缓存

**Comment by holmium** [comment]
功能已废弃
