### ISSUE TITLE
最新版出现错误....

### ISSUE THREAD

**Issue by greyjojo** [holmium/dnsforwarder#150]
MS是配置文件和程序之间HOST的小错误，无法运行！WIN7 64位........

**Comment by holmium** [comment]
什么样的错误？

**Comment by holmium** [comment]
这回应该可以了

**Comment by greyjojo** [comment]
下了最新的了，开始的配置显示已经正确了，但是一解析就出现程序关闭.......需要我的配置文件吗？应该是没有问题的，上一个版本是没有问题的。

**Comment by holmium** [comment]
能把程序输出贴一下吗？

**Comment by holmium** [comment]
还有Hosts的文件地址？

**Comment by greyjojo** [comment]
host是本地的，我没有用在线。
以下是显示的信息：
DNSforwarder mainly by holmium. Version 5.0.35 . License : GPL v3.
Time of compilation : Aug 14 2016 19:06:09.

Configure File : D:\Program Files\Dnsforwarder\dnsforwarder.config


Local working interface:127.0.0.1
Local working port:53
Local TCP is opened:No
Primary server:UDP
TCP Server:202.141.162.123:5353
TCP Server:208.67.220.220:443
UDP Server:61.128.128.68
UDP Server:208.67.222.222:5353
UDP Parallel Query:Yes
UDP Filter:Yes
Hosts File:file://D:/Program Files/Dnsforwarder/hosts
Use cache:Yes
Memory Cache:Yes
Ignore TTL:No

[INFO] Excluded & Disabled list initialized.
[INFO] Loading Appendhosts completed, 1 IPv4 Hosts, 0 IPv6 Hosts, 4 CName Redire
ctions, 2 items are excluded, 24 items point to GoodIPLists.
[INFO] Local hosts file : "D:\Temporary Windows Files\hosts"
[INFO] Loading the existing hosts file ...
[INFO] Loading hosts file completed, 108 IPv4 Hosts, 0 IPv6 Hosts, 9 CName Redir
ections, 0 items are excluded.
[INFO] UDP socket 127.0.0.1:53 created.
[INFO] Now you can set DNS to 127.0.0.1.
[INFO] Getting hosts from file://D:/Program Files/Dnsforwarder/hosts ...
[INFO] Hosts file://D:/Program Files/Dnsforwarder/hosts saved.
[INFO] Hosts saved at D:\Temporary Windows Files\hosts.
[INFO] Loading hosts file completed, 108 IPv4 Hosts, 0 IPv6 Hosts, 9 CName Redir
ections, 0 items are excluded.

**Comment by holmium** [comment]
host内容能提供一下吗？谢谢

**Comment by greyjojo** [comment]
#Short URL
www.google.com g.co
www.google.com goo.gl
www.youtube.com youtu.be
www.facebook.com fb.me
www.dropbox.com db.tt
104.244.42.197 t.co

#Other Websites
31.13.90.9 cx.atdmt.com
67.72.120.47 secure.footprint.net
72.14.246.169 app.simplenote.com
104.78.23.174 connect.facebook.net
72.14.249.180 ingress.com
180.97.235.30 urls.api.twitter.com
219.76.4.4 log.getdropbox.com

#Websites Redirection
www.google.com google.com
www.google.com www.youtube-nocookie.com
www.dropbox.com dropbox.com
www.tumblr.com tumblr.com

#Archive
207.241.224.22 archive.org
207.241.224.22 www.archive.org
207.241.226.190 web.archive.org

# Twitter
185.45.5.45 twitter.com
185.45.5.45 www.twitter.com
185.45.5.45 api.twitter.com
185.45.5.45 mobile.twitter.com
185.45.5.45 support.twitter.com
185.45.5.45 upload.twitter.com
185.45.5.45 tweetdeck.twitter.com
185.45.5.45 syndication.twitter.com
185.45.5.45 syndication-o.twitter.com
185.45.5.45 platform.twitter.com
185.45.5.45 about.twitter.com
185.45.5.45 blog.twitter.com
185.45.5.45 p.twitter.com
185.45.5.45 betastream.twitter.com
185.45.5.45 dev.twitter.com
185.45.5.45 pic.twitter.com
185.45.5.45 search.twitter.com
185.45.5.45 status.twitter.com
185.45.5.45 assets0.twitter.com
185.45.5.45 assets1.twitter.com
185.45.5.45 assets2.twitter.com
185.45.5.45 assets3.twitter.com
185.45.5.45 static.twitter.com
185.45.5.45 help.twitter.com
185.45.5.45 ton.twitter.com
185.45.5.45 s.twitter.com
185.45.5.45 analytics.twitter.com
185.45.5.45 urls-real.api.twitter.com
185.45.5.45 userstream.twitter.com
185.45.5.45 sitestream.twitter.com
185.45.5.45 stream.twitter.com
185.45.5.45 tdweb.twitter.com
173.236.110.98 twitpic.com
173.236.110.98 m1.twitpic.com
173.236.110.98 web1.twitpic.com
173.236.110.98 web10.twitpic.com
173.236.110.98 web2.twitpic.com
173.236.110.98 web3.twitpic.com
173.236.110.98 web4.twitpic.com
173.236.110.98 web5.twitpic.com
173.236.110.98 web6.twitpic.com
173.236.110.98 web7.twitpic.com
173.236.110.98 web8.twitpic.com
173.236.110.98 web9.twitpic.com
209.17.68.209 oi40.tinypic.com
209.17.68.209 oi41.tinypic.com
209.17.68.209 oi42.tinypic.com
209.17.68.209 oi43.tinypic.com
209.17.68.209 oi44.tinypic.com
209.17.68.209 oi45.tinypic.com
209.17.68.209 oi46.tinypic.com
209.17.68.209 oi47.tinypic.com
209.17.68.209 oi48.tinypic.com
209.17.68.209 oi49.tinypic.com
209.17.68.209 oi50.tinypic.com
209.17.68.209 oi51.tinypic.com
209.17.68.209 oi52.tinypic.com
209.17.68.209 oi53.tinypic.com
209.17.68.209 oi54.tinypic.com
209.17.68.209 oi55.tinypic.com
209.17.68.209 oi56.tinypic.com
199.96.57.3 a0.twimg.com
199.96.57.3 a1.twimg.com
199.96.57.3 video.twimg.com
199.96.57.3 abs.twimg.com
199.96.57.3 g.twimg.com
199.96.57.3 o.twimg.com
199.96.57.3 p.twimg.com
199.96.57.3 r.twimg.com
199.96.57.3 ma.twimg.com
199.96.57.3 pbs.twimg.com
199.96.57.3 si0.twimg.com
199.96.57.3 si1.twimg.com
199.96.57.3 si2.twimg.com
199.96.57.3 si3.twimg.com
199.96.57.3 si4.twimg.com
199.96.57.3 si5.twimg.com
199.96.57.3 ton.twimg.com
199.96.57.3 syndication.twimg.com
199.96.57.3 syndication-o.twimg.com
199.96.57.3 image-proxy-origin.twimg.com
199.96.57.3 si0.twimg.co
199.96.57.3 si1.twimg.co
199.96.57.3 si2.twimg.co
199.96.57.3 si3.twimg.co
199.96.57.3 si4.twimg.co
199.96.57.3 si5.twimg.co
104.244.42.132 tweetdeck.com
104.244.42.132 api.tweetdeck.com
104.244.42.132 web.tweetdeck.com
104.244.42.132 www.tweetdeck.com
104.244.42.132 downloads.tweetdeck.com
185.45.5.45 cdn.syndication.twimg.com
185.45.5.45 cdn.syndication.twitter.com
185.45.5.45 cdn.api.twitter.com
185.45.5.45 preview.cdn.twitter.com
185.45.5.45 apps.twitter.com

**Comment by greyjojo** [comment]
就是这样的！

**Comment by greyjojo** [comment]
随便提供我的配置文件：

# DNS 转发器的配置文件
# Configure File for dnsforwarder
# 此配置文件最好是 ANSI 编码的

# 相对路径的写法
# Windows：
# 支持用 `% %' 包围起来的相对路径，比如 `%SYSTEMROOT%\System32\drivers\etc\hosts'。
# `%PROGRAMDIRECTORY%' 表示程序所在的文件夹。
# Linux：
# 支持类似 `${HOME}' 的变量，比如 `${HOME}/hosts'。
# `${PROGRAMDIRECTORY}' 表示程序的配置文件夹，一般为 `/root/.dnsforwarder/'，执行 `dnsforwarder -p' 可以获得具体的位置。

##################################################
#
# 日志文件设置
#
##################################################

# LogOn <BOOLEAN>
# 是否打开文件日志输出 (since 5.0.4)
LogOn false

# LogFileThresholdLength <NUM>
# 单个日志文件大小的临界值（字节）(since 5.0.4)
# 当日志文件大小超过这个临界值后，当前的日志文件将会被重命名，然后建立一个新的日志文件，继续记录日志
LogFileThresholdLength 102400

# LogFileFolder <PATH>
# 设定日志文件所在的文件夹 (since 5.0.4)
# 日志文件初始的文件名为 `dnsforwarder.log'，当超过临界值之后，将会被重命名为 `dnsforwarder.log.1'、`dnsforwarder.log.2' 等等，然后重新建立一个 dnsforwarder.log' 文件
# 此路径的默认值为程序所在的文件夹（Windows）或程序的配置文件夹（Linux）
LogFileFolder

##################################################
#
# 本地
#
##################################################

# LocalInterface <IP>
# 设置在本地开启的界面，可以是本地回环地址 (127.0.0.1) ，本地局域网，以及互联网 (since 2.2)
# 如果是 IPv6 地址，请在地址两端加上方括号，例如 [::1] (本地回环)、[fe80::699c:f79a:9bb6:1] (since 2.3)
LocalInterface 127.0.0.1

# LocalPort <NUM>
# 本地开启的端口 (since 2.2)
LocalPort 53

# OpenLocalTCP <BOOLEAN>
# 在本地开启TCP，以便接收TCP协议的查询 (since 2.2)
# 可选值：`false' 或 `true'
OpenLocalTCP false

##################################################
#
# IP 选择策略
#
##################################################

#########################
# 服务器地址
#########################

# 您可以设置两组上游服务器，
# 一组是用 TCP 协议的服务器 (由 `TCPServer' 指定)，
# 另一组是用 UDP 协议的服务器 (由 `UDPServer' 指定)

# 选项 `PrimaryServer' 用来指定首选的服务器（同时也指定了协议）
# 任何不在排除列表中的域都会优先通过首选服务器及其协议来查询，
# 在排除列表中的域会优先使用另一组服务器并通过另一种协议查询。
# PrimaryServer
# 首选服务器 (since 2.2)
# 可选值：`TCP' 或 `UDP'
PrimaryServer UDP

# TCPServer <IP[:PORT]>
# 指定用 TCP 协议查询的上游服务器 (since 2.2)
# 可以指定多个服务器，服务器之间用半角逗号隔开 (since 2.3)
# 如果不加端口号，则默认为 53 (since 2.3)
# 例如 192.168.1.2:500 以及 4.2.2.2 (since 2.3)
# 对于IPv6地址，请在地址两端加方括号，例如 [2001:4860:4860::8888] 以及加端口的形式 [2001:4860:4860::8888]:53 (since 2.3)
TCPServer 202.141.162.123:5353,208.67.220.220:443

# TCPProxy <IP[:PORT]>
# 设置 TCP 查询时的 Socks5 代理服务器（试验功能） (since 5.0.11)
# 写法和 `TCPServer' 一样
# 可以指定多个服务器，服务器之间用半角逗号隔开
# 如果不加端口号，则默认为 1080
# 此选项如果不为空，则当通过 TCP 协议向上游服务器查询时，通过此选项设置的代理进行
# 如果此选项为空，则当通过 TCP 协议向上游服务器查询时，直接与服务器进行连接
# 此选项对通过 UDP 协议向上游服务器的查询无效
TCPProxy

# UDPServer <IP[:PORT]>
# 指定用 UDP 协议查询的上游服务器 (since 2.2)
# 可以指定多个服务器，服务器之间用半角逗号隔开 (since 2.3)
# 如果不加端口号，则默认为 53 (since 2.3)
# 例如 192.168.1.2:500 以及 4.2.2.2 (since 2.3)
# 对于IPv6地址，请在地址两端加方括号，例如 [2001:4860:4860::8888] 以及加端口的形式 [2001:4860:4860::8888]:53 (since 2.3)
UDPServer 61.128.128.68,208.67.222.222:5353

# DedicatedServer <DOMAIN1 SERVER_IP1>,<DOMAIN2 SERVER_IP2>,...
# 为某些域名指定专门的查询服务器，而不使用服务器列表（`TCPServer' 和 `UDPServer'）中的服务器 (since 2.5 b1)
# 格式为：域名 服务器地址
#
# 例如：DedicatedServer www.google.com 8.8.8.8
# 这样所有对域名 www.google.com 的查询都通过 8.8.8.8 这个服务器来进行
# 如果所指定的域名不在排除列表中，那么将通过 `PrimaryServer' 所指定的协议与服务器通讯，
# 否则将通过另一种协议与服务器通讯。
# 不同项之间用半角逗号 (`,') 分隔，同时注意最后不要有逗号
# 可以有多条 `DedicatedServer' 选项
DedicatedServer

#########################
# 服务器选项
#########################

# ParallelQuery <BOOLEAN>
# 是否启用 UDP 并发查询 (since 2.6 b1)
# 并发查询指的是，向所有指定的 UDP 服务器发送查询请求，取最先接受到的有效回复作为查询结果，并丢弃其余的回复
# 开启此选项必须保证 `UDPServer' 中的服务器都是 IPv4 或者都是 IPv6 的
# 此选项不影响 `DedicatedServer' 的设置，也就是说，对于已经指定专用服务器的域名，只通过专用服务器进行查询
# 可选值：`false' 或 `true'
ParallelQuery true

# UDPFilter <BOOLEAN>
# 是否开启 UDP 防污染 (since 2.6 b1)
# “防污染”指的是过滤伪造的 DNS 数据包
# 开启时需要保证 `UDPServer' 中存在国外的 DNS 服务器，如果配合使用 `UDPBlock_IP' 选项将大大提高过滤的精确度
# 可选值：`false' 或 `true'
UDPFilter true

# UDPBlock_IP <IP1>,<IP2>,.....
# 阻挡含有以下 IP 地址（支持 IPv4 和 IPv6 地址 (since 5.0.11) ）的 UDP DNS 数据包 (since 2.6 b1)
# 仅对通过 UDP 服务器查询而来的 DNS 数据包有效
# 以下列表中已经含有部分伪造的 IP 地址，可以执行 `dnsforwarder -P' 来获取更多伪造的 IP 地址
# 如果 `UDPFilter' 为 `false'，此选项无效
# IPv6 地址不用加方括号
UDPBlock_IP 243.185.187.39,46.82.174.68,37.61.54.158,93.46.8.89,59.24.3.173,203.98.7.65,8.7.198.45,78.16.49.15,159.106.121.75

# IPSubstituting <IP1 IP'1>,<IP2 IP'2>,.....
# 替换 DNS 数据包中的 IP 地址（只支持 IPv4 地址） (since 5.0.1)
# 例如：
# IPSubstituting 127.0.0.1 1.2.0.127
# 的效果是把 DNS 数据包中所有的 127.0.0.1 地址替换为 1.2.0.127
# 仅替换通过服务器（TCP 和 UDP）查询而来的 DNS 数据包，对于缓存中和 Hosts 中的结果无效
# 多条替换项目用半角逗号 (`,') 分隔，也可以写多行 `IPSubstituting'
IPSubstituting

#########################
# 排除列表
#########################

# ExcludedDomain <DOMAIN1>,<DOMAIN2>,.....
# 排除列表，每个域之间用半角逗号 (`,') 分隔，同时注意最后不要有逗号 (since 2.2)
# 支持通配符。 (since 2.2.2)
# 一个项目如果不含通配符，则从域名尾部开始匹配，例如 `123.com' 则会匹配所有以 `123.com' 结尾的域名。
# 如果含通配符则严格按照通配符来匹配。
# 可以有多条 `ExcludedDomain' 选项 (since 2.2.2)
ExcludedDomain hxg.cc

# ExcludedList <PATH>
# 从文件载入到排除列表 (since 5.0.3)
ExcludedList

# AlwaysUDP <DOMAIN1>,<DOMAIN2>,.....
# 将这些域名始终通过 UDP 查询，无论 `PrimaryServer' 是如何设置的 (since 5.0.18)
AlwaysUDP

# AlwaysTCP <DOMAIN1>,<DOMAIN2>,.....
# 将这些域名始终通过 TCP 查询，无论 `PrimaryServer' 是如何设置的 (since 5.0.18)
AlwaysTCP

#########################
# IP 列表（仅支持 IPv4 地址）
#########################
# IP 列表用于自动检测一组 IP 地址，将相应最快的 IP 地址甄选出来

# GoodIPList <NAME> <INTERVAL>
# 定义一个 IP 列表，<NAME> 为改列表的名称，<INTERVAL> 为检测列表中 IP 地址有效性的间隔时间（毫秒）
# 例如：
# GoodIPList list1 60000
GoodIPList google 21600000
GoodIPList facebook 21600000
GoodIPList dropbox 21600000

# GoodIPListAddIP <LIST_NAME> <IP:PORT>
# 向一个 IP 列表中添加 IP 地址
# 例如：
# GoodIPListAddIP list1 120.0.0.1:80
GoodIPListAddIP google IP我自己保留了
GoodIPListAddIP google 
GoodIPListAddIP google 
GoodIPListAddIP google 
GoodIPListAddIP google  
GoodIPListAddIP google 
GoodIPListAddIP google 
GoodIPListAddIP facebook 
GoodIPListAddIP facebook 
GoodIPListAddIP facebook 
GoodIPListAddIP dropbox 
GoodIPListAddIP dropbox 
GoodIPListAddIP dropbox 
GoodIPListAddIP dropbox 

#########################
# Hosts
#########################

# Hosts <STRING>
# Hosts 文件的 URL，可以是本地 Hosts 文件 (以 file:// 开头，支持相对路径)，也可以是网络上的 Hosts 文件 (以 http:// 或者 https:// 开头)。 (since 5.0.5)
# 例如 file://C:/Windows/System32/drivers/etc/hosts 或 file:///etc/hosts 或 http://xxx.com/hosts
# 可以指定多个 Hosts，以半角逗号（`,'）分隔，也可以写多条 `Hosts'，路径两头不要加引号
# 在 Hosts 文件中，支持通配符 (`*' 和 `?') (只能在域名中出现通配符)
# Hosts 文件必须是原始格式，不能是压缩文件或者 HTML 文件
# Hosts 文件最好是 ANSI 编码的
# Hosts 中的 IPv6 地址不用加方括号
# 如果保留为空，则不从文件载入 Hosts
Hosts file://D:/Program Files/Dnsforwarder/hosts

# HostsUpdateInterval <NUM>
# 重新载入 Hosts 文件的间隔时间，秒 (since 2.2)
# -1 表示不重新载入
# 如果保留为空，则使用默认值 (18000)
HostsUpdateInterval -1

# HostsDownloadPath <PATH>
# Hosts 文件的下载到本地文件的路径 (不是文件夹路径) (since 2.2)
# 例如 C:\Windows\Temp\hosts 或者 /tmp/hosts
# 支持相对路径 (since 5.0.3)
# 如果文件存在则覆盖
# 如果保留为空，则默认在与程序所在相同的文件夹内（Windows）或程序的配置文件夹内（Linux）
HostsDownloadPath D:\Temporary Windows Files\hosts

# HostsScript <PATH>
# 在每次下载完 Hosts 文件后、加载 Hosts 文件之前执行的脚本 (since 2.2)
# 支持相对路径 (since 5.0.3)
# 如果保留为空，则不执行脚本
HostsScript

# HostsRetryInterval <NUM>
# 当网络 Hosts 下载失败后的重试时间，秒 (since 2.2.2)
# 仅对网络 Hosts 有效
# 如果保留为空，则使用默认值 (30)
HostsRetryInterval 30

# AppendHosts <HOSTS>,<HOSTS>,...
# 附加的 hosts，即使 `Hosts' 选项为空也照样载入 (since 2.2.2)
# <HOSTS> 的写法与文件中的一样，同样支持通配符
# IPv6 地址不用加方括号
# 多条 hosts 可以用半角逗号分隔开，也可以写多条 `AppendHosts'
# 比如可以写成:
#  AppendHosts 127.0.0.1 123.com,127.0.0.1 456.com,1.2.3.4 foobar.*
# 也可以分多条写:
#  AppendHosts 127.0.0.1 123.com
#  AppendHosts 127.0.0.1 456.com
#  AppendHosts 1.2.3.4 foobar.*
#
# 也可以定义指向一个 IP 列表的 Hosts 项（仅支持 IPv4 地址），例如：
#  AppendHosts <list1> www.123.com
# 此时 www.123.com 将会指向 list1 中最快的 IP 地址。
#
# 也可以定义 CName 的 Hosts 项，例如：
#  AppendHosts www.google.cn *.google.com
# 这样所有匹配 *.google.com 的域名都将指向 www.google.cn 的 IP 地址 (since 2.3)
#
# 如果使某些域名跳过在 hosts 中的查询，可以
#  AppendHosts @@ *.012345.com
# 这样所有匹配 *.012345.com 的域名都不会在 hosts 中查询
#
# 各种 hosts 的优先级从高到低
# 带 `@@' 的禁止项
# 一般 hosts 项
# CName hosts 项
# 在以上的基础上：
# `AppendHosts' 指定的 hosts 比 `Hosts' 配置选项指定的文件中的 hosts 的优先级高
# 排在越前的 `Hosts' 项优先级越高
# 排在越前的 hosts 条目优先级越高
AppendHosts @@ google.cn
AppendHosts @@ *.google.cn
AppendHosts <google> *.youtube.com
AppendHosts <google> *.ytimg.com
AppendHosts <google> *.google.*
AppendHosts <google> *.google.*.*
AppendHosts <google> *.google*.com
AppendHosts <google> *.gstatic.com
AppendHosts <google> *.ggpht.com
AppendHosts <google> *.gmodules.com
AppendHosts <google> *.gvt*.com
AppendHosts <google> *.gmail.com
AppendHosts <google> *.blogger.com
AppendHosts <google> *.blogspot.com
AppendHosts <google> *.android.com
AppendHosts <google> *.chromium.org
AppendHosts <google> *.tumblr.com 
AppendHosts <google> feedburner.com
AppendHosts <google> gcr.io
AppendHosts <google> appspot.com
AppendHosts <google> golang.org
AppendHosts <facebook> *.facebook.com
AppendHosts <facebook> *.fbsbx.com
AppendHosts <facebook> *.thefacebook.com
AppendHosts 192.0.78.12 *.fb.com
AppendHosts <dropbox> *.dropbox.com
AppendHosts <dropbox> *.dropbox*.com
AppendHosts appspot.com *.appspot.com
AppendHosts gcr.io *.gcr.io
AppendHosts golang.org *.golang.org
AppendHosts feedburner.com *.feedburner.com

# DisableIpv6WhenIpv4Exists <BOOLEAN>
# 如果一个域名在 Hosts 被指定了一个 IPv4 地址（包括文件 Hosts 和 `AppendHosts' 指定的 Hosts），那么拒绝对这个域名的 IPv6 地址查询 (since 5.0.12)
DisableIpv6WhenIpv4Exists false

##################################################
#
# 缓存控制
#
##################################################

# UseCache <BOOLEAN>
# 是否使用缓存（默认为文件缓存） (since 2.2)
# 可选值：`false' 或 `true'
UseCache true

# CacheSize <NUM>
# 缓存大小 (字节)
# 缓存大小不能小于 102400 (100KB) (since 2.3)
CacheSize 1048576

# MemoryCache <BOOLEAN>
# 是否使用内存缓存，而不是文件缓存 (since 2.3.2)
# 如果 `UseCache' 为 `false'，此选项无效
# 可选值：`false' 或 `true'
MemoryCache true

# CacheFile <PATH>
# 手工指定缓存文件 (不是文件夹) (since 2.3)
# 支持相对路径 (since 5.0.3)
# 如果保留为空，则默认在与程序所在相同的文件夹内（Windows）或程序的配置文件夹内（Linux）
# 如果 `MemoryCache' 为 `true'，此选项无效
CacheFile

# IgnoreTTL <BOOLEAN>
# 是否忽略 TTL (since 2.2)
# 可选值：`false' 或 `true'
# 为 `true' 时将忽略 TTL，此时所有的缓存条目将不会被移除
# 为 `false' 时不忽略 TTL，缓存条目将会按照 TTL 的时间来移除
# 当 `UseCache' 的值为 `false' 时，此选项无效
IgnoreTTL false

# OverrideTTL <NUM>
# 强制使所有缓存的条目的 TTL 为 <NUM> (since 2.2)
# 若 <NUM> 为 -1，则表示不进行强制
# 当 `UseCache' 的值为 `false' 时，此选项无效
# 此选项等同于 `CacheControl * fixed <NUM>' (since 5.0.18)
OverrideTTL -1

# MultipleTTL <NUM>
# 将所有缓存条目的 TTL 加倍，倍数为 <NUM> (since 2.2)
# 当 `UseCache' 的值为 `false' 时，此选项无效
# 当 `IgnoreTTL' 的值为 `true' 时，此选项无效
# 此选项等同于 `CacheControl * vari <NUM>x+0' (since 5.0.18)
MultipleTTL 1

# CacheControl <DOMAIN> [$[$]]<TYPE> [ARGUMENT]
# 控制域名 <DOMAIN> 的缓存行为 (since 5.0.18)
# 如果缓存未开启，则此选项无效
# <DOMAIN> 是域名；[$[$]] 是传染设定；<TYPE> 是类型；[ARGUMENT] 是参数
# <DOMAIN> 支持通配符，支持尾部匹配
# <TYPE> 有以下可选项（均为小写）：
#  orig    : 使用原先的 TTL，即不改变指定域名记录的 TTL，此类型无需 [ARGUMENT] 参数
#  nocache : 不缓存指定域名记录，此类型无需 [ARGUMENT] 参数
#  fixed   : 将指定域名记录的 TTL 修改为一个预先指定的常数值，这个值通过 [ARGUMENT] 参数指定
#  vari    : 将指定域名记录的 TTL 修改为一个预先规定的变量，这个变量通过 [ARGUMENT] 参数指定，此时 [ARGUMENT] 参数的格式为 `ax+b'，其中 a、b 为非负整数（需用户手工指定），x 为记录原先的 TTL 值（不需要用户指定）。此选项必须为 `ax+b' 的形式，不能是 `ax-b' 或者其它的变体形式
#
# 示例：
# CacheControl baidu.com orig # 不改变以 `baidu.com' 结尾的域名的 TTL
# CacheControl 163.com nocache # 不缓存以 `163.com' 结尾的域名
# CacheControl qq.com fixed 500 # 把所有以 `qq.com' 结尾的域名的 TTL 修改为 500
# CacheControl sina.com.cn vari 2x+200 # 把所有以 `sina.com.cn' 结尾的域名的 TTL 的值修改为 2x+200，其中 x 是域名记录原先的 TTL 值
#
# 传染机制：
# 某些域名有 CName 记录，例如 www.windowsupdate.com：
# ;; QUESTION SECTION:
# ;www.windowsupdate.com.		IN	A
#
# ;; ANSWER SECTION:
# www.windowsupdate.com.	3585	IN	CNAME	windowsupdate.microsoft.nsatc.net.      （记录一）
# windowsupdate.microsoft.nsatc.net. 285 IN CNAME	www.update.microsoft.com.nsatc.net. （记录二）
# www.update.microsoft.com.nsatc.net. 285	IN A	134.170.58.222                      （记录三）
# www.update.microsoft.com.nsatc.net. 285	IN A	65.55.50.157                        （记录四）
#
# 如果仅仅指定了 `www.windowsupdate.com' 的缓存控制，那么 `windowsupdate.microsoft.nsatc.net' 和 `www.update.microsoft.com.nsatc.net' 的记录以什么规则进行处理？是继承 `www.windowsupdate.com' 的缓存设置，还是使用自己专门的设置（如果有的话）？
# 可以指定传染机制来解决这个问题
# 有以下传染机制（以 `www.windowsupdate.com' 为例）：
#  主动传染 : 所有的域名记录不论是否存在单独指定的控制条目，均使用 `www.windowsupdate.com' 的控制条目
#  被动传染 : 如果存在单独指定的控制条目，那么使用单独指定的控制条目，否则使用 `www.windowsupdate.com' 的控制条目
#  不传染   : 如果存在单独指定的控制条目，那么使用单独指定的控制条目，如果没有则不修改记录的 TTL 值
# 只有被查询的域名控制条目才具有传染性质
# 写法：
#  主动传染 （此为默认情况）:
#   CacheControl www.windowsupdate.com fixed 1000
#   CacheControl 163.com orig
#  被动传染（<TYPE> 前加一个 `$'）:
#   CacheControl www.windowsupdate.com $fixed 1500
#   CacheControl sina.com.cn $nocache
#  不传染（<TYPE> 前加两个 `$'）:
#   CacheControl www.windowsupdate.com $$fixed 2000
#   CacheControl windowsupdate.microsoft.nsatc.net $$vari 2x+100
#
# 示例（仍然以 `www.windowsupdate.com' 为例）：
#  CacheControl www.windowsupdate.com fixed 1000
#  CacheControl windowsupdate.microsoft.nsatc.net fixed 500
#  效果是：记录一、二、三和四的 TTL 都会被修改为 1000
#
#  CacheControl www.windowsupdate.com $fixed 1000
#  CacheControl windowsupdate.microsoft.nsatc.net fixed 500
#  效果是：记录一、三和四的 TTL 会被修改为 1000，记录二的 TTL 会被修改为 500
#
#  CacheControl www.windowsupdate.com $$fixed 1000
#  CacheControl windowsupdate.microsoft.nsatc.net fixed 500
#  效果是：记录一的 TTL 会被修改为 1000，记录二的 TTL 会被修改为 500，记录三和四的 TTL 不会被修改

# ReloadCache <BOOLEAN>
# 当程序启动后是否重新载入已有的文件缓存 (since 2.2.3)
# 已有的缓存大小必须和 `CacheSize' 所指定的大小相等
# 可选值：`false' 或 `true'
# 如果 `MemoryCache' 的值为 `true'，此选项无效
ReloadCache false

# OverwriteCache <BOOLEAN>
# 如果已有的文件缓存无法重载，是否直接将其覆盖掉 (since 2.3)
# 可选值：`false' 或 `true'
# 如果 `MemoryCache' 的值为 `true'，此选项无效
# 如果 `ReloadCache' 的值为 `false'，此选项无效
OverwriteCache false

##################################################
#
# 杂项
#
##################################################

# DisabledType <NUM1>,<NUM2>,.....
# 禁止查询的 DNS 类型列表，每个类型（用数字代表）之间用半角逗号 (`,') 分隔 (since 2.2)
# 所有的 DNS 类型：
# A	      1   IPv4 地址
# AAAA       28   IPv6 地址
# APL        42
# CERT       37
# CNAME       5
# DHCID      49
# DLV     32769
# DNAME      39
# DNSKEY     48
# DS	     43
# HIP        55
# IPSECKEY   45
# KEY        25
# KX	     36
# LOC        29
# MX	     15
# NAPTR      35
# NS	      2   Name Server
# NSEC       47
# NSEC3      50
# NSEC3PARAM 51
# PTR        12   Domain pointer
# RRSIG      46
# RP	     17
# SIG        24
# SOA         6   start of authority record
# SPF        99
# SRV        33
# SSHFP      44
# TA	  32768
# TKEY      249
# TSIG      250
# TXT        16
# ANY       255
# AXFR      252
# IXFR      251
# OPT        41
DisabledType

# DisabledDomain <DOMAIN1>,<DOMAIN2>,.....
# 禁止查询的域列表，每个域之间用半角逗号 (`,') 分隔 (since 2.2)
# 支持通配符。 (since 2.2.2)
# 一个项目如果不含通配符，则从域名尾部开始匹配，例如 `123.com' 则会匹配所有以 `123.com' 结尾的域名。
# 如果含通配符则严格按照通配符来匹配。
# 可以有多条DisabledDomain (since 2.2.2)
DisabledDomain

# DisabledList <PATH>
# 从文件载入到禁用列表 (since 5.0.3)
DisabledList

# RefusingResponseCode <NUM>
# 当拒绝一次查询（`DisabledType' 或者 `DisabledDomain'）的时候所返回的状态码 (since 2.6 b1)
# 状态码  描述
# 0       No error condition
# 1       Format error
# 2       Server failure
# 3       Name Error (NXDOMAIN)
# 4       Not Implemented
# 5       Refused
# 参见 RFC 1035，`4.1.1. Header section format'，`Response code'
RefusingResponseCode 0

# DomainStatistic <BOOLEAN>
# 是否启用域名统计 (since 2.5 b1)
# 域名信息统计会依照模板文件记录域名的查询情况
# 记录的结果在与程序所在相同的文件夹内（Windows）或程序的配置文件夹内（Linux）的`statistic.html'文件内
# 可选值：`false' 或 `true'
DomainStatistic false

# DomainStatisticTempletFile <PATH>
# 域名统计的模板文件路径 (since 5.0.23)
# 如果保留为空，则默认为与程序所在相同的文件夹内（Windows）或程序的配置文件夹内（Linux）的`StatisticTemplate.html'文件 
DomainStatisticTempletFile

# StatisticInsertionPosition <STRING>
# 指定在模板文件中写入的位置 (since 5.0.23)
# 如果保留为空，则默认为`'
# StatisticInsertionPosition 

# StatisticUpdateInterval <NUM>
# 域名统计刷新时间间隔（秒） (since 2.5 b1)
StatisticUpdateInterval 29

**Comment by holmium** [comment]
感谢，非常感谢！
问题应该解决了，但是可能还有其它的问题，改天检查一下代码。最近打算重写一部分模块，之前的代码实在太乱了。

**Comment by greyjojo** [comment]
您辛苦了！
