### ISSUE TITLE
例如路由重新拨号，或者路由重启后，DNSforwarder就不能解析了。

### ISSUE THREAD

**Issue by Saeviome** [holmium/dnsforwarder#151]
我用的win版的。昨晚专门测试了一下，睡前重启了一下路由，电脑没关机，结果到了早上，发现还是无法解析。始终是下面这样。没办法只能重启DNSforwarder。

C:\nslookup baidu.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
**\* 请求 UnKnown 超时

**Comment by holmium** [comment]
重启路由后本机IP地址变了吗？本机监听的是哪个地址？程序输出能贴一下吗？

**Comment by Saeviome** [comment]
程序最小化运行的。本机IP是固定IP。本机监听的127.0.0.1:53

**Comment by Saeviome** [comment]
另外在cmd里查询被和谐的网址，第一次总是超时。一旦查询了国内网址后，就不会超时了（和谐的也不超时）

C:\Users\Sae>nslookup google.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    google.com
Addresses:  2404:6800:4005:802::200e
          216.58.199.110


C:\Users\Sae>nslookup google.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    google.com
Addresses:  2404:6800:4005:802::200e
          216.58.199.110


C:\Users\Sae>nslookup baidu.com
1.0.0.127.in-addr.arpa
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 600 (10 mins)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    baidu.com
Addresses:  180.149.132.47
          220.181.57.217
          111.13.101.208
          123.125.114.144


C:\Users\Sae>nslookup google.com
1.0.0.127.in-addr.arpa
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 600 (10 mins)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    google.com
Addresses:  2404:6800:4005:802::200e
          216.58.199.110


C:\Users\Sae>nslookup youtube.com
1.0.0.127.in-addr.arpa
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 600 (10 mins)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    youtube.com
Addresses:  200:2:cb62:741::
          216.58.199.110

**Comment by Saeviome** [comment]
刚刚又测试了一下。开着DNSforwarder的窗口。
```
DNSforwarder mainly by holmium. Version 5.0.36 . License : GPL v3.
Time of compilation : Aug 14 2016 22:38:45.

Configure File : D:\Software\浏览器＆阅读器\Proxy Tools\DNSforwarder\dnsforwarder.config


Local working interface:127.0.0.1
Local working port:53
Local TCP is opened:No
Primary server:UDP
TCP Server:8.8.4.4
TCP Server:8.8.8.8
UDP Server:216.146.36.36
UDP Server:208.67.220.220
UDP Server:8.8.8.8
UDP Server:114.114.114.114
UDP Parallel Query:Yes
UDP Filter:Yes
Use cache:No
Memory Cache:Yes
Ignore TTL:No

[INFO] Excluded & Disabled list initialized.
[INFO] UDP socket 127.0.0.1:53 created.
[INFO] Now you can set DNS to 127.0.0.1.
```

然后在路由里重新拨号上网。
接着在cmd里查询任何网址都是超时。
而此刻DNSforwarder窗口里什么反应都没有，还是上面的信息。
过了一会儿就突然蹦出了下面这样的一堆数据。应该是浏览器和其他应用发送的DNS请求。


Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qex.f.360.cn] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][find.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][find.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][find.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][find.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][ip.netmon.360safe.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][hn15-feapp.lol.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][ip.netmon.360safe.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][qtreport.qq.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][ip.netmon.360safe.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][server19402.teamviewer.com] Timed o
ut.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][server19402.teamviewer.com] Timed o
ut.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][ip.netmon.360safe.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][server19402.teamviewer.com] Timed o
ut.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][server19402.teamviewer.com] Timed o
ut.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.
Aug 20 15:44:15 [U][127.0.0.1][IPv4 Address][stat.game.yy.com] Timed out.

**Comment by holmium** [comment]
可以排除掉防火墙或者路由器的原因吗？

**Comment by Saeviome** [comment]
系统未开防火墙。路由是多播，但是我觉得和多播没关系。因为路由拨上号就能上网。换其他公共dns都能解析，只是DNSforwarder就像卡主了一样，直接不联网了。很奇怪。
你哪里难道不能重现这样的问题么？

**Comment by holmium** [comment]
我这里确实无法重现

**Comment by Saeviome** [comment]
应该是我win7系统的问题，也不知道出的什么怪毛病

**Comment by badstar** [comment]
我也有同样的问题

**Comment by holmium** [comment]
这个应该已经解决了
