### ISSUE TITLE
关于HOST的一个重复功能.....觉得有点画蛇添足了。

### ISSUE THREAD

**Issue by greyjojo** [holmium/dnsforwarder#153]
当保存HOST的文件夹和本地HOST在同一个目录的时候，本地HOST读取后也会生成一个TXT文件，不再同一个目录的时候会在指定目录生成另外HOST文件.......其实我认为没有必要生成TXT文件，或者另外一个完全相同的HOST文件啊.....莫非是用来备份的？？？？？

**Comment by holmium** [comment]
简单的说，是为了程序逻辑的简单，本地和网络用同一套逻辑就行
