### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by badstar** [holmium/dnsforwarder#156]
gcc  -pthread  -DDOWNLOAD_LIBCURL  -O2   -pthread  -o dnsforwarder addresschunk.o checkip.o dnsrelated.o hosts.o simpleht.o querydnslistentcp.o addresslist.o domainstatistic.o internalsocket.o socketpool.o querydnslistenudp.o array.o debug.o downloader.o ipchunk.o statichosts.o readconfig.o bst.o dnscache.o excludedlist.o linkedqueue.o stringchunk.o readline.o cacheht.o dnsgenerator.o main.o stringlist.o querydnsbase.o request_response.o cachettlcrtl.o dnsparser.o goodiplist.o utils.o querydnsinterface.o stablebuffer.o  -lcurl -lm -lm

request_response.o：在函数‘InitBlockedIP’中：
request_response.c:(.text+0x1340)：对‘IPMisc_Init’未定义的引用
request_response.o：在函数‘InitIPSubstituting’中：
request_response.c:(.text+0x142c)：对‘IPMisc_Init’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by holmium** [comment]
先用旧版本的吧，这一块还没有commit

**Comment by holmium** [comment]
这个应该已经修复了
