### ISSUE TITLE
UDPBlock_IP 不工作了

### ISSUE THREAD

**Issue by badstar** [holmium/dnsforwarder#157]
新版本编译出来后貌似UDPBlock_IP不工作了，同样的配置文件换回老版本就正常了

**Comment by holmium** [comment]
有时间看看，抱歉

**Comment by badstar** [comment]
顺便提一下，之前编译的 d48f6aa 版本，运行一段时间后感觉被UDPBlock_IP命中的域名就会超时无法解析了，但是同时其他域名是可以正常解析的，杀掉进程后重启会恢复正常。

**Comment by holmium** [comment]
被UDPBlock_IP命中的是不会返回给请求端的

**Comment by badstar** [comment]
UDPServer 180.168.255.118,116.228.111.18,8.8.8.8,8.8.4.4
UDPBlock_IP 8.7.198.45,89.31.55.106,93.46.8.89

我的意思是，在 d48f6aa 版本config中这样写，开始是运行正常的，查询被block的域名也可以得到正确的ip，启动后过上一段时间（可能24h以上），再解析 www.facebook.com 这样的域名就会查询超时不返回任何结果，但是同时www.163.com这样的域名仍然是可以正常解析的。
然后同样的config在现在的版本中编译出来，www.facebook.com查询就会返回 93.46.8.89 的错误ip。

**Comment by holmium** [comment]
无法重现，能否把完整的配置文件发一下？

**Comment by badstar** [comment]
这是现在用的config文件，在 d48f6aa 版本可以正常工作，新版本不行
[config.txt](https://github.com/holmium/dnsforwarder/files/531548/config.txt)

**Comment by holmium** [comment]
已修复

**Comment by badstar** [comment]
编译了一下91e4d66 ，facebook仍然返回 93.46.8.89 的错误IP

**Comment by holmium** [comment]
依然无法重现

**Comment by holmium** [comment]
似乎在Linux下是有问题的

**Comment by holmium** [comment]
找到问题了

**Comment by holmium** [comment]
这回应该可以了，您再试试？

**Comment by badstar** [comment]
可以了，谢谢！
