### ISSUE TITLE
输错误的域名会跳转到运营商的网站

### ISSUE THREAD

**Issue by wangbolizhong** [holmium/dnsforwarder#160]
错误的域名会转到华数的网站。
![2016 10 19_20h33m47s_002_](https://cloud.githubusercontent.com/assets/11750269/19518890/03d49a6e-963c-11e6-928b-ede2560d7f70.jpg)
New session
[INFO] Excluded & Disabled list initialized.
[INFO] UDP socket 127.0.0.1:53 created.
[INFO] Now you can set DNS to 127.0.0.1.
Oct 19 20:34:54 [U][127.0.0.1][IPv4 Address][sacsxcasxasxasx.com] : 53 bytes
   IPv4 Address:30.250.11.135
Oct 19 20:34:54 [U][127.0.0.1][IPv4 Address][www.hzcnc.com] : 104 bytes
   Canonical Name:B3L8375A3RVSQxrhJtEkt0vT6E0loUdT.aliyunwaf.com
   IPv4 Address:120.55.234.244

**Comment by holmium** [comment]
上游服务器问退
