### ISSUE TITLE
能否实现一个功能?被UDPBlock_IP阻挡的查询,自动用TCPServer重新查询?

### ISSUE THREAD

**Issue by asdyjd** [holmium/dnsforwarder#164]
应用环境,我这里PrimaryServer是国内的UDP,翻墙DNS用服务器用的8.8.8.8的TCP.通过Shadowsocks代理查询.
能不能增加这个功能,被UDPBLOCK_IP阻挡的,自动再通过TCP去查询?
我现在用的是AlwaysTCP翻墙,但是那些被墙的域名很多啊!写出来超长的.而且用AlwaysTCP好像也总出现一些问题.比如我发现,我必须把imgcache.qq.com写进AlwaysTCP.否则就不能解析这个域名,真是不知道问题在哪.我还必须把alicdn.com写进去,否则上淘宝,物品页不能正常显示卖家的信用,还有一些其他的奇奇怪怪的.
我的配置大概是这样的:
'''
PrimaryServer UDP
TCPProxy 127.0.0.1:1080
TCPServer 8.8.4.4,8.8.8.8
UDPServer 223.5.5.5,223.6.6.6
AlwaysTCP 这里一大堆域名.
'''

**Comment by asdyjd** [comment]
真是见了鬼了,我运行dig imgcache.qq.com @随便一个IP,都会得到10.6.0.126.
10.6.0.126是一个局域网内的IP啊!
感觉很可能是学校也过滤DNS请求了.
而我通过代理,得到的就是正常的.

**Comment by holmium** [comment]
不能加入太方便使用的功能，否则这个软件就很有可能废掉，抱歉

**Comment by asdyjd** [comment]
确实是学校把imgcache.qq.com屏蔽了.
dig imgcache.qq.com @114.114.114.114
得到10.6.0.126
dig imgcache.qq.com @114.114.114.114 +tcp
就正常了.
这说明学校屏蔽了.

但是上面我说的那个功能可以解决这个问题.通过正常解析得到的IP,如果是UDPBLOCK_IP里的,重新用TCP解析.
能帮忙实现这功能吗?这功能很有用!
