### ISSUE TITLE
把程序换成dnsforwarder6中的客户端，就无法解析网址了

### ISSUE THREAD

**Issue by Kitfly** [holmium/dnsforwarder#169]
换回dnsforwarder5中的客户端，一切恢复正常。

是不是两个版本的dnsforwarder.config的格式不同呢？

求教。
Thx~

**Comment by holmium** [comment]
是的，两个版本的配置文件格式不同

**Comment by Kitfly** [comment]
不知道新版的配置文件模板在哪里找呢？

Thx~

**Comment by holmium** [comment]
wiki里有的

**Comment by holmium** [comment]
https://github.com/holmium/dnsforwarder/blob/6/default.config

**Comment by Kitfly** [comment]
Thanks!
