### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#170]
建议6系保留5系 文件载入排除列表的功能，便于配置文件的编辑

UDPGroup <IP1[:PORT],IP2[:PORT],...> <DOMAIN1,DOMAIN2,...> <on|off>
<DOMAIN1,DOMAIN2,...>在配置文件中编辑容易出错，也无取反功能（Acrylic DNS Proxy有取反）。

类似5系配置
ExcludedDomain <DOMAIN1>,<DOMAIN2>,.....   
ExcludedList < PATH > 
从文件载入到排除列表 (since 5.0.3) 
ExcludedList %PROGRAMDIRECTORY%\ExcludedDomain.txt

最好可以对应多条UDPGroup，并增加取反功能
UDPGroup <IP1[:PORT],IP2[:PORT],...> <PATH:Domain1.txt,ExcludedDomain1.txt> <on|off>
UDPGroup <IP1[:PORT],IP2[:PORT],...> <PATH:Domain2.txt,ExcludedDomain2.txt> <on|off>

**Comment by yuanyouyin** [comment]
例如：
UDPGroup 114.114.114.114 *.55188.com,*.ijinshan.com,*.liebao.cn,*.windowsupdate.*,sjs.sinajs.cn off
UDPGroup 223.5.5.5 *.kafan.cn,*.ijinshan.com,*.*liebao*.*,*.*duba*.*,*.*alibabagroup.com,*.*taobao*.*,*.*tmall.com,*.*1688.com,*.*alimama.com,*.*alitrip.com,*.*aliyun.com,*.*alicdn.com,*.*yunos.com,*.*www.net.cn,*.*autonavi.com,*.*uc.cn,*.*kanbox.com,*.*xiami.com,*.*ttpod.com,*.*laiwang.com,*.*dingtalk.com,*.*11main.com,*.*alipay.com off
UDPGroup 180.76.76.76 *.*baidu*.com,*.bdstatic.*,*.ijinshan.com,*.*liebao*.*,*.*duba*.*,*.163.com off
UDPGroup 119.29.29.29 *.vc52.cn,*.*qq*.*,*.*dnspod.cn,*.*tencent.com,*.browser.qq.com,*.qlogo.cn,qlogo.cn,*.weiyun.com,weiyun.com,*.qq.com,qq.com,*.qpic.cn,qpic.cn,*.gtimg.cn,gtimg.cn,*.tencent.com,tencent.com,*.qqmail.com,qqmail.com,*.qzone.com,qzone.com,*.soso.com,soso.com,*.foxmail.com,foxmail.com,*.gtimg.com,gtimg.com off
UDPGroup 159.226.118.1 *.org.cn,*.edu.cn,*.gov.cn off
UDPGroup 120.27.215.80,8.8.4.4,113.57.148.218,202.103.44.150 * on

**Comment by yuanyouyin** [comment]
以上简单配置，就很复杂。
再比如如下配置，远远表达得不够
TCPGroup 120.27.215.80,139.129.206.51,8.8.8.8,208.67.220.220,156.154.70.1,208.67.220.220 avstats.avira.com,dispatch.avira-update.com,*.avira*.com,,autoproxy-gfwlist.googlecode.com,*.*dnscrypt.org,micasmica.blogspot.com,*gfwli.st,gpsonextra.net,*.gotocdn.com,*.amazonaws.com,blog.yadgen.com,onedrive.live.com,*.onedrive.live.com,*.g.cn,*.blogspot.com,*.blogger.com,*.youtube.com,*.youtube-nocookie.com,*.gstatic.com,*.ytimg.com,redirector.gvt1.com,*.gvt1.com,*.*google*.*,*.*github*.*,att.newsmth.net,*.goo.gl,*.feedsportal.com,*.wikipedia.org,*.twitter.com,*.facebook.com no

**Comment by holmium** [comment]
从文件载入列表可以考虑支持，

顺便问一下，取反是什么？

**Comment by yuanyouyin** [comment]
就是排除的意思，取反列表中DOMAIN被排除查询

**Comment by yuanyouyin** [comment]
AcrylicConfiguration.ini中的说明：它可以定义10组DNS

[GlobalSection]
PrimaryServerAddress=8.8.8.8  设置主DNS服务器地址（支持IPV4和IPV6）
PrimaryServerPort=53  设置主DNS端口
PrimaryServerProtocol=UDP 设置主DNS解析协议 TCP/UDP/SOCKS5
PrimaryServerProxyAddress=  设置远程解析服务器地址
PrimaryServerProxyPort=  设置远程解析服务器端口
PrimaryServerDomainNameAffinityMask=^*.com;^*.org;*
; 主DNS要查询的特定域名和排除域名配置说明和示例（支持 * 通配符 + ^ 排除符）
; The cluster of domain names the primary DNS server is to resolve.
; The affinity mask is a list of semicolon separated values  or  wildcards  that
; allows to restrict which DNS server is going to resolve a particular host
; name.
; In the following example only the requests for domain names ending with ".com"
; get forwarded to the primary DNS server:
; PrimaryServerDomainNameAffinityMask=*.com
; In the following example only the requests for domain names ending with ".com"
; and ".org" get forwarded to the primary DNS server:
; PrimaryServerDomainNameAffinityMask=*.com;*.org
; Negations can be expressed by prepending a caret (^) to the value or wildcard.
; In the following example only the requests for domain names  NOT  ending  with
; ".com" or ".org" get forwarded to the primary DNS server (the  last  catch-all
; value is particularly important in this case as, if missing, no request  would
; ever be forwarded to the primary DNS server):
; PrimaryServerDomainNameAffinityMask=^*.com;^*.org;*
PrimaryServerQueryTypeAffinityMask=A;CNAME;MX;NS;SOA;SRV    DNS查询的类型
IgnoreNegativeResponsesFromPrimaryServer=No

SecondaryServerAddress=8.8.4.4
SecondaryServerPort=53
SecondaryServerProtocol=UDP
SecondaryServerProxyAddress=
SecondaryServerProxyPort=
SecondaryServerDomainNameAffinityMask=
SecondaryServerQueryTypeAffinityMask=
IgnoreNegativeResponsesFromSecondaryServer=No

……

DenaryServerAddress=
DenaryServerPort=53
DenaryServerProtocol=UDP
DenaryServerProxyAddress=
DenaryServerProxyPort=
DenaryServerDomainNameAffinityMask=
DenaryServerQueryTypeAffinityMask=
IgnoreNegativeResponsesFromDenaryServer=No

**Comment by yuanyouyin** [comment]
关于Acrylic DNS Proxy
http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

**Comment by holmium** [comment]
好的，谢谢！

**Comment by holmium** [comment]
现在可以用 GroupFile 选项了

**Comment by yuanyouyin** [comment]
谢谢，辛苦了！

**Comment by yuanyouyin** [comment]
有很多如下错误提示，何故
An error occured while receiving from UDP client 127.0.0.1, not a big deal.

**Comment by holmium** [comment]
这个没关系
