### ISSUE TITLE
新版（昨天）出现无法加载Hosts提示

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#174]
Feb 15 09:24:25 [INFO] Hosts j saved.
Feb 15 09:24:25 [ERROR] Getting Hosts p悕 failed. Waiting 30 second(s) to try again.

设置：
Hosts file://%PROGRAMDIRECTORY%/hosts_user_defined.txt
Hosts http://某网/ghosts/dnsforwarder/hosts.txt

**Comment by holmium** [comment]
已经定位问题，下一版本解决，抱歉给您带来不便

**Comment by holmium** [comment]
这个应该已经修复了
