### ISSUE TITLE
AppendHosts @@无效

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#177]
AppendHosts @@ program-thinker.blogspot.hk

访问program-thinker.blogspot.hk。日志输出仍然 Feb 24 11:13:03 [H][127.0.0.1][IPv4 Address][program-thinker.blogspot.hk] ，貌似AppendHosts @@ 不起作用。

**Comment by holmium** [comment]
看了看确实忘记实现了，下一版本加上

**Comment by yuanyouyin** [comment]
辛苦了。

**Comment by holmium** [comment]
最新版应该已经没问题了

**Comment by yuanyouyin** [comment]
测试已正常
