### ISSUE TITLE
HostsScript <PATH> 无效

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#178]
dnsforwarder.config配置：
HostsScript %PROGRAMDIRECTORY%\Start.vbs

Start.vbs：
Wscript.CreateObject("Wscript.Shell").run "cmd /k cd /d %~dp0&EditHosts.bat",vbhide

EditHosts.bat：
@ECHO OFF&PUSHD %~DP0
copy Hosts.txt 1B.txt
sed -i "/localhost/d" 1B.txt
sed -i "/ip6/d" 1B.txt
copy 1B.txt Hosts.txt
del /f 1B.txt
EXIT  >NUL 2>NUL

程序目录内有sed.exe文件。
单纯运行Start.vbs，Hosts能正常编辑。

**Comment by holmium** [comment]
我看看

**Comment by holmium** [comment]
有这行输出吗？
    Running hosts script ...

**Comment by holmium** [comment]
直接
HostsScript %PROGRAMDIRECTORY%\EditHosts.bat

不行吗？

**Comment by yuanyouyin** [comment]
有Running hosts script ...；
直接
HostsScript %PROGRAMDIRECTORY%\EditHosts.bat 无反应

**Comment by yuanyouyin** [comment]
另 总有 [INFO] Unrecognisable host : ﻿, it may be too long.输出不知何故。

**Comment by holmium** [comment]
可以把完整的输出贴一下吗？

**Comment by yuanyouyin** [comment]
Feb 26 14:53:08 [INFO] New session.
Feb 26 14:53:08 [INFO] Running on daemon mode.
Feb 26 14:53:08 [INFO] UDP interface 127.0.0.1:53 opened.
Feb 26 14:53:08 [INFO] Disabled domains initialized.
Feb 26 14:53:08 [INFO] Disabled types initialized.
Feb 26 14:53:08 [INFO] Disabled list initialized.
Feb 26 14:53:08 [INFO] Local hosts file : "D:\Program Files\DNSForwarder\hosts.txt"
Feb 26 14:53:08 [INFO] Loading the existing hosts file ...
Feb 26 14:53:08 [INFO] Unrecognisable host : ﻿, it may be too long.
Feb 26 14:53:08 [INFO] Loading hosts completed.
Feb 26 14:53:08 [INFO] Getting hosts from various places ...
Feb 26 14:53:08 [INFO] Cache File : D:\Program Files\DNSForwarder\cache
Feb 26 14:53:08 [INFO] Hosts file://D:\Program Files\DNSForwarder\/hosts_user_defined.txt saved.
Feb 26 14:53:08 [INFO] Server groups initialized.
Feb 26 14:53:08 [U][127.0.0.1][IPv4 Address][heartnn.coding.me] : 459 bytes
   Canonical Name:pages.coding.net
   IPv4 Address:23.248.162.81
   IPv4 Address:23.91.101.48
   IPv4 Address:23.91.96.71
   IPv4 Address:23.91.100.83
   IPv4 Address:23.91.97.43
   IPv4 Address:23.248.162.83
   IPv4 Address:110.79.20.235
   IPv4 Address:23.91.97.161
   IPv4 Address:23.91.97.251
   IPv4 Address:23.91.100.254
   IPv4 Address:23.248.162.91
   IPv4 Address:23.91.100.78
   IPv4 Address:23.91.96.142
   IPv4 Address:23.248.162.138
   IPv4 Address:23.91.101.50
   IPv4 Address:23.91.96.134
   IPv4 Address:23.248.162.196
   IPv4 Address:23.91.100.100
   IPv4 Address:23.91.98.182
   Name Server:lv3ns1.ffdns.net
   Name Server:lv3ns2.ffdns.net
   Name Server:lv3ns4.ffdns.net
   Name Server:lv3ns3.ffdns.net
Feb 26 14:53:08 [INFO] Hosts http://heartnn.coding.me/hosts/dnsforwarder/hosts.txt saved.
Feb 26 14:53:08 [INFO] Hosts saved at D:\Program Files\DNSForwarder\hosts.txt.
Feb 26 14:53:08 [INFO] Running hosts script ...
Feb 26 14:53:08 [INFO] Unrecognisable host : ﻿, it may be too long.
Feb 26 14:53:09 [INFO] Loading hosts completed.
Feb 26 14:53:34 [U][127.0.0.1][IPv4 Address][teredo.ipv6.microsoft.com] : 170 bytes

**Comment by yuanyouyin** [comment]
#########################
# Hosts
#########################

# Hosts <STRING>
# Hosts 文件的 URL，可以是本地 Hosts 文件 (以 file:// 开头，支持相对路径)，也可以是网络上的 Hosts 文件 (以 http:// 或者 https:// 开头)。 (since 5.0.5)
# 例如 file://C:/Windows/System32/drivers/etc/hosts 或 file:///etc/hosts 或 http://xxx.com/hosts
# 写多条 `Hosts' 可以指定多个 Hosts 文件，路径两头不要加引号
# 在 Hosts 文件中，支持通配符 (`*' 和 `?') (只能在域名中出现通配符)
# Hosts 文件必须是原始格式，不能是压缩文件或者 HTML 文件
# Hosts 文件最好是 ANSI 编码的
# Hosts 中的 IPv6 地址不用加方括号
# 如果保留为空，则不从文件载入 Hosts
# Hosts
Hosts file://%PROGRAMDIRECTORY%/hosts_user_defined.txt
# Hosts file://%PROGRAMDIRECTORY%/Hosts Update/Hosts.txt
Hosts http://heartnn.coding.me/hosts/dnsforwarder/hosts.txt

# HostsUpdateInterval <NUM>
# 重新载入 Hosts 文件的间隔时间，秒 (since 2.2)
# -1 表示不重新载入
# 如果保留为空，则使用默认值 (18000=5h)
HostsUpdateInterval 18000

# HostsDownloadPath <PATH>
# Hosts 文件的下载到本地文件的路径 (不是文件夹路径) (since 2.2)
# 例如 C:\Windows\Temp\hosts 或者 /tmp/hosts
# 支持相对路径 (since 5.0.3)
# 如果文件存在则覆盖
# 如果保留为空，则默认在与程序所在相同的文件夹内（Windows）或程序的配置文件夹内（Linux）
# HostsDownloadPath %PROGRAMDIRECTORY%\hosts
HostsDownloadPath

# HostsScript <PATH>
# 在每次下载完 Hosts 文件后、加载 Hosts 文件之前执行的脚本 (since 2.2)
# 支持相对路径 (since 5.0.3)
# 如果保留为空，则不执行脚本
HostsScript %PROGRAMDIRECTORY%\EditHosts.bat

# HostsRetryInterval <NUM>
# 当网络 Hosts 下载失败后的重试时间，秒 (since 2.2.2)
# 仅对网络 Hosts 有效
# 如果保留为空，则使用默认值 (30)
HostsRetryInterval 30

# AppendHosts <HOSTS>,<HOSTS>,...
# 附加的 hosts，即使 `Hosts' 选项为空也照样载入 (since 2.2.2)
# <HOSTS> 的写法与文件中的一样，同样支持通配符
# IPv6 地址不用加方括号
# 多条 hosts 可以用半角逗号分隔开，也可以写多条 `AppendHosts'
# 比如可以写成:
#  AppendHosts 127.0.0.1 123.com,127.0.0.1 456.com,1.2.3.4 foobar.*
# 也可以分多条写:
#  AppendHosts 127.0.0.1 123.com
#  AppendHosts 127.0.0.1 456.com
#  AppendHosts 1.2.3.4 foobar.*
#
# 也可以定义指向一个 IP 列表的 Hosts 项（仅支持 IPv4 地址），例如：
#  AppendHosts <list1> www.123.com
# 此时 www.123.com 将会指向 list1 中最快的 IP 地址。
#
# 也可以定义 CName 的 Hosts 项，例如：
#  AppendHosts www.google.cn *.google.com
# 这样所有匹配 *.google.com 的域名都将指向 www.google.cn 的 IP 地址 (since 2.3)
#
# 如果使某些域名跳过在 hosts 中的查询，可以
#  AppendHosts @@ *.012345.com
# 这样所有匹配 *.012345.com 的域名都不会在 hosts 中查询
#
# 各种 hosts 的优先级从高到低
# 带 `@@' 的禁止项
# 一般 hosts 项
# CName hosts 项
# 在以上的基础上：
# `AppendHosts' 指定的 hosts 比 `Hosts' 配置选项指定的文件中的 hosts 的优先级高
# 排在越前的 `Hosts' 项优先级越高
# 排在越前的 hosts 条目优先级越高
# AppendHosts @@ program-thinker.blogspot.hk
# AppendHosts 216.58.217.205 accounts.google.com
# AppendHosts @@ www.google.cn,@@ www.g.cn

# BlockIpv6WhenIpv4Exists <BOOLEAN>
# 如果一个域名在 Hosts 被指定了一个 IPv4 地址（包括文件 Hosts 和 `AppendHosts' 指定的 Hosts），那么拒绝对这个域名的 IPv6 地址查询 (since 5.0.12, renamed after 6.0.0)
BlockIpv6WhenIpv4Exists false

**Comment by holmium** [comment]
把EditHosts.bat内容改成
```
echo 12345678901234567890
```

再运行一下，看看有什么输出？

**Comment by yuanyouyin** [comment]
Feb 26 17:12:41 [INFO] New session.
Feb 26 17:12:41 [INFO] Running on daemon mode.
Feb 26 17:12:41 [INFO] UDP interface 127.0.0.1:53 opened.
Feb 26 17:12:41 [INFO] Disabled domains initialized.
Feb 26 17:12:41 [INFO] Disabled types initialized.
Feb 26 17:12:41 [INFO] Disabled list initialized.
Feb 26 17:12:41 [INFO] Local hosts file : "D:\Program Files\DNSForwarder\hosts.txt"
Feb 26 17:12:41 [INFO] Loading the existing hosts file ...
Feb 26 17:12:41 [INFO] Unrecognisable host : ﻿, it may be too long.
Feb 26 17:12:41 [INFO] Loading hosts completed.
Feb 26 17:12:41 [INFO] Getting hosts from various places ...
Feb 26 17:12:41 [INFO] Cache File : D:\Program Files\DNSForwarder\cache
Feb 26 17:12:41 [INFO] Hosts file://D:\Program Files\DNSForwarder\/hosts_user_defined.txt saved.
Feb 26 17:12:41 [INFO] Server groups initialized.
Feb 26 17:12:41 [U][127.0.0.1][IPv4 Address][heartnn.coding.me] : 459 bytes
   Canonical Name:pages.coding.net
   IPv4 Address:23.91.97.43
   IPv4 Address:23.91.100.83
   IPv4 Address:23.91.97.161
   IPv4 Address:23.248.162.81
   IPv4 Address:23.91.100.78
   IPv4 Address:23.91.100.100
   IPv4 Address:23.91.96.71
   IPv4 Address:23.91.100.254
   IPv4 Address:23.91.98.182
   IPv4 Address:110.79.20.235
   IPv4 Address:23.248.162.196
   IPv4 Address:23.248.162.91
   IPv4 Address:23.91.96.142
   IPv4 Address:23.248.162.138
   IPv4 Address:23.91.97.251
   IPv4 Address:23.248.162.83
   IPv4 Address:23.91.101.50
   IPv4 Address:23.91.96.134
   IPv4 Address:23.91.101.48
   Name Server:lv3ns2.ffdns.net
   Name Server:lv3ns1.ffdns.net
   Name Server:lv3ns4.ffdns.net
   Name Server:lv3ns3.ffdns.net
Feb 26 17:12:42 [INFO] Hosts http://heartnn.coding.me/hosts/dnsforwarder/hosts.txt saved.
Feb 26 17:12:42 [INFO] Hosts saved at D:\Program Files\DNSForwarder\hosts.txt.
Feb 26 17:12:42 [INFO] Running hosts script ...
Feb 26 17:12:42 [INFO] Unrecognisable host : ﻿, it may be too long.
Feb 26 17:12:43 [INFO] Loading hosts completed.

**Comment by yuanyouyin** [comment]
没有反应

**Comment by yuanyouyin** [comment]
EditHosts.bat内容改成为

echo 12345678901234567890
pause

**Comment by holmium** [comment]
dnsforwarder是怎么启动的？

**Comment by holmium** [comment]
有没有装防护墙之类的软件？

**Comment by yuanyouyin** [comment]
重启批处理：
@echo off
setlocal enabledelayedexpansion
ECHO.
title 删除缓存并重新启动DnsForwarder
cd /d %~dp0
cd /d D:\Program Files\DNSForwarder
taskkill /f /IM DNSForwarder.exe 1>nul 2>nul
del /f /q "Cache" >NUL 2>NUL
echo 已删除缓存。。。
del /f /q "R:\dnsforwarder.*" >NUL 2>NUL
ping -n 2 10>nul
echo 已删除DnsForwarder日志。。。
dnsforwarder.exe -d
ECHO.&ECHO.已重新启动DnsForwarder！
Exit >NUL 2>NUL

**Comment by yuanyouyin** [comment]
自动启动.reg
Windows Registry Editor Version 5.00
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]
"DNSFORWARDER"="\"D:\\Program Files\\DNSForwarder\\DNSForwarder.exe\" -d"

**Comment by yuanyouyin** [comment]
Avira,未装防火墙（用系统的，win7 X64）

**Comment by yuanyouyin** [comment]
DNSForwarder.exe进程被信任（Avira中）

**Comment by holmium** [comment]
暂时无法重现

**Comment by yuanyouyin** [comment]
HostsScript %PROGRAMDIRECTORY%\test.bat

目前的问题是配置HostsScript后，EditHosts.bat根本没有运行，你那里也不能再现可以执行么？

比如PROGRAMDIRECTORY下创建：test.bat
@ECHO OFF&PUSHD %~DP0
copy Hosts.txt 1B.txt
EXIT

程序目录PROGRAMDIRECTORY存在Hosts.txt，但1B.txt能不能出现就能简单测试了。

**Comment by holmium** [comment]
我可以执行

**Comment by yuanyouyin** [comment]
@echo off
setlocal enabledelayedexpansion
ECHO.
title 删除缓存并重新启动DnsForwarder
cd /d %~dp0
cd /d D:\Program Files\DNSForwarder
taskkill /f /IM DNSForwarder.exe 1>nul 2>nul
del /f /q "Cache" >NUL 2>NUL
echo 已删除缓存。。。
del /f /q "R:\dnsforwarder.*" >NUL 2>NUL
ping -n 2 10>nul
echo 已删除DnsForwarder日志。。。
dnsforwarder.exe -d
ECHO.&ECHO.已重新启动DnsForwarder！
Exit >NUL 2>NUL

很奇怪，我用这个脚本2年了，发现新版本偶尔不能重启DNSForwarder.exe，并造成CMD（系统命令行提示符）也一闪而过（无法进入界面）

**Comment by yuanyouyin** [comment]
windows7 64位系统

**Comment by yuanyouyin** [comment]
是不是因为路径中有空格不识别？
新版有如下日志
Mar 11 21:09:55 [INFO] Local hosts file : "D:\Program Files\DNSForwarder\hosts.t
xt"
Mar 11 21:09:55 [INFO] Loading the existing hosts file ...
Mar 11 21:09:55 [INFO] Unrecognisable host : 锘? it may be too long.
Mar 11 21:09:55 [INFO] Loading hosts completed.
Mar 11 21:09:55 [INFO] Getting hosts from various places ...
Mar 11 21:09:55 [INFO] Cache File : D:\Program Files\DNSForwarder\cache
Mar 11 21:09:55 [INFO] Reloading the cache ...
Mar 11 21:09:55 [INFO] Cache reloaded, containing 0 entries for 0 items.
Mar 11 21:09:55 [INFO] Server groups initialized.
Mar 11 21:09:55 [INFO] Hosts file://D:\Program Files\DNSForwarder\/Hosts Update/
Hosts.txt saved.
Mar 11 21:09:55 [INFO] Hosts file://D:\Program Files\DNSForwarder\/hosts_user_de
fined.txt saved.
Mar 11 21:09:55 [INFO] Hosts saved at D:\Program Files\DNSForwarder\hosts.txt.
Mar 11 21:09:55 [INFO] Running hosts script "D:\Program Files\DNSForwarder\\Edit
Hosts.bat"...
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Mar 11 21:09:56 [INFO] Unrecognisable host : 锘? it may be too long.
Mar 11 21:09:56 [INFO] Loading hosts completed.

**Comment by yuanyouyin** [comment]
命令行窗口：
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\yuanyouyin>D:\Program Files\DNSForwarder\EditHosts.bat
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

下列命令增加“”号后可以正确运行
C:\Users\yuanyouyin>"D:\Program Files\DNSForwarder\EditHosts.bat"

# HostsScript <PATH>
下列两种配置均无法运行
HostsScript %PROGRAMDIRECTORY%\EditHosts.bat
HostsScript "%PROGRAMDIRECTORY%\EditHosts.bat"

**Comment by holmium** [comment]
#182
