### ISSUE TITLE
编译 --enable-android 出错，求教

### ISSUE THREAD

**Issue by heartnn** [holmium/dnsforwarder#179]
export PATH=/home/heartnn/aarch64-linux-android/bin:$PATH
export CC=aarch64-linux-android-gcc
export CXX=aarch64-linux-android-g++

heartnn@ubuntu:~/Downloads/dnsforwarder$ ./configure --enable-downloader=wget --enable-static --enable-android --host=ubuntu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for ubuntu-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for ubuntu-gcc... aarch64-linux-android-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether aarch64-linux-android-gcc accepts -g... yes
checking for aarch64-linux-android-gcc option to accept ISO C89... none needed
checking whether aarch64-linux-android-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of aarch64-linux-android-gcc... gcc3
checking for log in -lm... yes
checking for sqrt in -lm... yes
checking for pow... yes
checking for sqrt... yes
checking how to run the C preprocessor... aarch64-linux-android-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking wordexp.h usability... no
checking wordexp.h presence... no
checking for wordexp.h... no
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... cross
configure: WARNING: result yes guessed because of cross compilation
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... no
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... no
checking for setenv... yes
checking for wordexp... no
configure: WARNING: Relative path is not supported.
checking for setenv... (cached) yes
checking for wordexp... (cached) no
checking for clock_gettime... yes
checking for inet_ntoa... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for select... yes
checking for socket... yes
checking for strchr... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strstr... yes
checking for pid_t... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for size_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

heartnn@ubuntu:~/Downloads/dnsforwarder$ make
make  all-am
make[1]: Entering directory `/home/heartnn/Downloads/dnsforwarder'
aarch64-linux-android-gcc  -pthread  -DANDROID  -DDOWNLOAD_WGET  -static   -pthread  -o dnsforwarder addresslist.o dynamichosts.o main.o array.o mcontext.o filter.o stablebuffer.o bst.o mmgr.o goodiplist.o statichosts.o cacheht.o hcontext.o pipes.o stringchunk.o cachettlcrtl.o hosts.o ptimer.o stringlist.o hostscontainer.o tcpm.o dnscache.o hostsutils.o readconfig.o timedtask.o dnsgenerator.o iheader.o readline.o udpfrontend.o dnsparser.o ipchunk.o udpm.o dnsrelated.o ipmisc.o simpleht.o utils.o domainstatistic.o linkedqueue.o socketpool.o winmsgque.o downloader.o logs.o socketpuller.o  -lm -lm 
addresslist.o: In function `AddressList_GetPtrListOfFamily':
addresslist.c:(.text+0x454): undefined reference to `rpl_malloc'
addresslist.o: In function `AddressList_GetPtrList':
addresslist.c:(.text+0x520): undefined reference to `rpl_malloc'
addresslist.c:(.text+0x550): undefined reference to `rpl_malloc'
dynamichosts.o: In function `DynamicHosts_Load':
dynamichosts.c:(.text+0x40): undefined reference to `rpl_malloc'
main.o: In function `main':
main.c:(.text+0xd20): undefined reference to `rpl_malloc'
array.o:array.c:(.text+0x68): more undefined references to `rpl_malloc' follow
utils.o: In function `SafeRealloc':
utils.c:(.text+0x78): undefined reference to `rpl_realloc'
utils.o: In function `StringDup':
utils.c:(.text+0xd28): undefined reference to `rpl_malloc'
domainstatistic.o: In function `GetPreAndPost':
domainstatistic.c:(.text+0x78): undefined reference to `rpl_malloc'
linkedqueue.o: In function `LinkedQueue_Add':
linkedqueue.c:(.text+0x40): undefined reference to `rpl_malloc'
downloader.o: In function `GetFromInternet_MultiFiles':
downloader.c:(.text+0x30): undefined reference to `rpl_malloc'
downloader.o: In function `GetFromInternet_SingleFile':
downloader.c:(.text+0x330): undefined reference to `rpl_malloc'
collect2: error: ld returned 1 exit status
make[1]: *** [dnsforwarder] Error 1
make[1]: Leaving directory `/home/heartnn/Downloads/dnsforwarder'
make: *** [all] Error 2

**Comment by holmium** [comment]
这个问题我看搜一下就有解决方法

**Comment by heartnn** [comment]
解决了，仔细看了一遍配置，犯了低级错误
