### ISSUE TITLE
求教：AppendHosts配置中 <list1>规则如何写

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#180]
AppendHosts配置中 <list1>规则如何写，能给个例子么？
```
# 也可以定义指向一个 IP 列表的 Hosts 项（仅支持 IPv4 地址），例如：
#  AppendHosts <list1> www.123.com
# 此时 www.123.com 将会指向 list1 中最快的 IP 地址。
```

另问：
下列日志中，
Mar 06 15:56:27 [H][127.0.0.1][IPv4 Address][maps.googleapis.com] : 789 bytes
   IPv4 Address:211.66.248.131
   IPv4 Address:61.91.161.217
   IPv4 Address:64.233.188.188
   IPv4 Address:64.233.188.188
   IPv4 Address:64.233.188.188
   IPv4 Address:64.233.188.188
   IPv4 Address:61.91.161.217
   IPv4 Address:61.91.161.217
   IPv4 Address:61.91.161.217
   IPv4 Address:64.233.189.128
   IPv4 Address:61.91.161.217
   IPv4 Address:61.91.161.217
   IPv4 Address:61.91.161.217

本例中[maps.googleapis.com]将会指向最快的 IP 地址的吧？

**Comment by holmium** [comment]
```
#########################
# IP 列表（仅支持 IPv4 地址）
#########################
# IP 列表用于自动检测一组 IP 地址，将相应最快的 IP 地址甄选出来

# GoodIPList <NAME> <INTERVAL>
# 定义一个 IP 列表，<NAME> 为改列表的名称，<INTERVAL> 为检测列表中 IP 地址有效性的间隔时间（毫秒）
# 例如：
#  GoodIPList list1 60000

# GoodIPListAddIP <LIST_NAME> <IP:PORT>
# 向一个 IP 列表中添加 IP 地址
# 例如：
#  GoodIPListAddIP list1 120.0.0.1:80
```

**Comment by yuanyouyin** [comment]
如下配置是否正确？

#########################
# IP 列表（仅支持 IPv4 地址）
#########################
# IP 列表用于自动检测一组 IP 地址，将相应最快的 IP 地址甄选出来

# GoodIPList <NAME> <INTERVAL>
# 定义一个 IP 列表，<NAME> 为改列表的名称，<INTERVAL> 为检测列表中 IP 地址有效性的间隔时间 60000=1min（毫秒）
# 例如：
GoodIPList list1 60000

# GoodIPListAddIP <LIST_NAME> <IP:PORT>
# 向一个 IP 列表中添加 IP 地址
# 例如：
#  GoodIPListAddIP list1 120.0.0.1:80

# 也可以定义指向一个 IP 列表的 Hosts 项（仅支持 IPv4 地址），例如：
# AppendHosts <list1> www.123.com
AppendHosts <list1> www.google.com
# 此时 www.123.com 将会指向 list1 中最快的 IP 地址。


但访问www.google.com时出现   DNSFwarder.exe已停止工作

有助于描述该问题的文件:
  R:\TEMP\WERB924.tmp.WERInternalMetadata.xml
  R:\TEMP\WERC6CB.tmp.appcompat.txt
  R:\TEMP\WERC71A.tmp.mdmp

**Comment by holmium** [comment]
还需要GoodIPListAddIP选项，向list1中添加IP。

**Comment by yuanyouyin** [comment]
OK ,谢谢。

另问：
下列日志中，
Mar 06 15:56:27 [H][127.0.0.1][IPv4 Address][maps.googleapis.com] : 789 bytes
IPv4 Address:211.66.248.131
IPv4 Address:61.91.161.217
IPv4 Address:64.233.188.188
IPv4 Address:64.233.188.188
IPv4 Address:64.233.188.188
IPv4 Address:64.233.188.188
IPv4 Address:61.91.161.217
IPv4 Address:61.91.161.217
IPv4 Address:61.91.161.217
IPv4 Address:64.233.189.128
IPv4 Address:61.91.161.217
IPv4 Address:61.91.161.217
IPv4 Address:61.91.161.217

本例中[maps.googleapis.com]将会指向最快的 IP 地址的吧？

**Comment by holmium** [comment]
本程序是返回所有IP的，没有选择最快的IP
