### ISSUE TITLE
HostsScript <PATH> 无效的原因貌似找到

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#182]
HostsScript <PATH> 无效的原因

是不是因为路径中有空格不识别？

新版有如下日志
Mar 11 21:09:55 [INFO] Hosts saved at D:\Program Files\DNSForwarder\hosts.txt.
Mar 11 21:09:55 [INFO] Running hosts script "D:\Program Files\DNSForwarder\Edit
Hosts.bat"...
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Mar 11 21:09:56 [INFO] Unrecognisable host : 锘? it may be too long.
Mar 11 21:09:56 [INFO] Loading hosts completed.

windows命令行窗口测试如下：
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\yuanyouyin>D:\Program Files\DNSForwarder\EditHosts.bat
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

下列命令增加“”号后可以正确运行
C:\Users\yuanyouyin>"D:\Program Files\DNSForwarder\EditHosts.bat"

本程序配置文件测试：
下列两种配置均无法运行
HostsScript %PROGRAMDIRECTORY%\EditHosts.bat
HostsScript "%PROGRAMDIRECTORY%\EditHosts.bat"

**Comment by yuanyouyin** [comment]
最新测试：
HostsScript D:\"Program Files"\DNSForwarder\EditHosts.bat
能正常运行

**Comment by holmium** [comment]
谢谢，下一版本解决这个问题，十分感谢！

**Comment by holmium** [comment]
这里确实找到个bug
