### ISSUE TITLE
HostsScript <PATH>貌似问题没有解决

### ISSUE THREAD

**Issue by yuanyouyin** [holmium/dnsforwarder#183]
可执行：HostsScript D:\ "Program Files"\DNSForwarder\EditHosts.bat
问题依旧：HostsScript D:\Program Files\DNSForwarder\EditHosts.bat
                       HostsScript %PROGRAMDIRECTORY%\EditHosts.bat

**Comment by holmium** [comment]
两头加引号应该就行了

**Comment by yuanyouyin** [comment]
DNSforwarder mainly by holmium. Version 6.1.10 . License : GPL v3.
Time of compilation : Mar 16 2017 15:35:32.

Configure File : D:\Program Files\DNSForwarder\dnsforwarder.config


Mar 17 13:20:27 [INFO] New session.
Mar 17 13:20:27 [INFO] UDP interface 127.0.0.1:53 opened.
Mar 17 13:20:27 [INFO] Disabled domains initialized.
Mar 17 13:20:27 [INFO] Disabled types initialized.
Mar 17 13:20:27 [INFO] Disabled list initialized.
Mar 17 13:20:27 [INFO] Loading Appendhosts completed.
Mar 17 13:20:27 [INFO] Local hosts file : "D:\Program Files\DNSForwarder\hosts.t
xt"
Mar 17 13:20:27 [INFO] Loading the existing hosts file ...
Mar 17 13:20:28 [INFO] Unrecognisable host : 锘? it may be too long.
Mar 17 13:20:28 [INFO] Loading hosts completed.
Mar 17 13:20:28 [INFO] Getting hosts from various places ...
Mar 17 13:20:28 [INFO] Cache File : D:\Program Files\DNSForwarder\cache
Mar 17 13:20:28 [INFO] Reloading the cache ...
Mar 17 13:20:28 [INFO] Cache reloaded, containing 100 entries for 89 items.
Mar 17 13:20:28 [INFO] Server groups initialized.
Mar 17 13:20:28 [INFO] Hosts file://D:\Program Files\DNSForwarder\/hosts_user_de
fined.txt saved.
Mar 17 13:20:28 [INFO] Hosts saved at D:\Program Files\DNSForwarder\hosts.txt.
Mar 17 13:20:28 [INFO] Running hosts script ""%PROGRAMDIRECTORY%\EditHosts.bat""
...
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Mar 17 13:20:28 [INFO] Unrecognisable host : 锘? it may be too long.
Mar 17 13:20:28 [INFO] Loading hosts completed.
Mar 17 13:20:44 [U][127.0.0.1][IPv4 Address][tips.ime.baidu.com] : 84 bytes
   Canonical Name:tips.ime.n.shifen.com
   IPv4 Address:180.97.33.174

**Comment by holmium** [comment]
试试用最新版定位一下问题

**Comment by yuanyouyin** [comment]
设置：
HostsScript %PROGRAMDIRECTORY%\EditHosts.bat

日志：
Mar 22 11:13:04 [INFO] Hosts file://D:\Program Files\DNSForwarder\/hosts_user_de
fined.txt saved.
Mar 22 11:13:04 [INFO] Hosts saved at D:\Program Files\DNSForwarder\hosts.txt.
Mar 22 11:13:04 [INFO] Running hosts script "D:\Program Files\DNSForwarder\\Edit
Hosts.bat"...
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Mar 22 11:13:04 [INFO] Unrecognisable host : 锘? it may be too long.
Mar 22 11:13:04 [INFO] Loading hosts completed.

**Comment by holmium** [comment]
HostsScript "%PROGRAMDIRECTORY%\EditHosts.bat"

**Comment by yuanyouyin** [comment]
是的

**Comment by holmium** [comment]
那不就解决了吗

**Comment by yuanyouyin** [comment]
谢谢
