### ISSUE TITLE
V6配置文件的“服务器地址”写法问题

### ISSUE THREAD

**Issue by StrollStars** [holmium/dnsforwarder#188]
请问下，V6的配置文件，“服务器地址”部分可否恢复V5的写法？
因为对大多数人而言，无论是黑白域名名单，都会采用网上现成的，V5的方式更方便更新。在V5现有的排除列表基础上，如果能够支持多个排除列表文件就更好了。
或者在V6现有的基础上，域名部分能够支持列表文件（最好是多个），那样也可以。

PS：可否在可执行文件的属性中添加版本号，方便比对、匹配和更新。

**Comment by holmium** [comment]
V6支持文件

**Comment by StrollStars** [comment]
尝试一：使用GroupFile
> # 井号后面写注释
> protocol udp    # 指定协议为 UDP
> server 114.114.114.114    # 这里写服务器地址
> parallel on    # 是否开启并发查询，“on” 或者 “off”
> 
> # 以下是域名，一行一个
> %PROGRAMDIRECTORY%\myudpdomain1.conf
> %PROGRAMDIRECTORY%\myudpdomain2.conf
> 
> # 井号后面写注释
> protocol tcp    # 指定协议为 TCP
> server 8.8.4.4,8.8.8.8    # 这里写服务器地址
> proxy 127.0.0.1    # Socks5 代理服务器，不同服务器之间用半角逗号分隔，或者写“no”代表不使用代理
> 
> # 以下是域名，一行一个
> *
所有解析都走UDP。

尝试二：不使用GroupFile
> UDPGroup 114.114.114.114 %PROGRAMDIRECTORY%\myudpdomain1.conf on
> UDPGroup 114.114.114.114 %PROGRAMDIRECTORY%\myudpdomain2.conf on
> TCPGroup 8.8.4.4,8.8.8.8 * 127.0.0.1
所有解析都走TCP。

请教：我想对两个列表（以后列表个数可能会增加）中的域名强制走UDP协议，其余协议全走TCP协议，该如何设置？

**Comment by holmium** [comment]
首先域名就是域名，不能指向文件。

然后第一种情况需要把两部分分成两个文件来写。

**Comment by StrollStars** [comment]
谢谢提醒，那我现在该如何从文件加载域名呢？也就是V5中的排除列表那样。

**Comment by holmium** [comment]
列表文件是如何获取的？如果是手工编辑那直接写到GroupFile中也无妨。如果是脚本自动获取，我觉得再把文件头部加几行内容也不是什么麻烦事。
支持文件就指GroupFile。

**Comment by StrollStars** [comment]
我都是手工下载覆盖旧版文件的，谢谢多次解答。
