### ISSUE TITLE
Hosts 优先级别并非最高

### ISSUE THREAD

**Issue by yyy8888** [holmium/dnsforwarder#189]
hosts有如下条目：
203.208.43.120	fonts.gstatic.com

dnsforwarder.config配置文件中
# AppendHosts @@ maps.gstatic.*,@@ ditu.google.*
并未排除fonts.gstatic.com

日志输出文件：
Jun 06 16:58:52 [U][127.0.0.1][IPv4 Address][fonts.gstatic.com] : 135 bytes
   Canonical Name:gstaticadssl.l.google.com
   IPv4 Address:203.208.41.63
   IPv4 Address:203.208.41.47
   IPv4 Address:203.208.41.55
   IPv4 Address:203.208.41.56

**Comment by holmium** [comment]
请贴完整的配置文件和程序输出
