### ISSUE TITLE
请教一下6版本的服务器组的优先级问题

### ISSUE THREAD

**Issue by liuxb** [holmium/dnsforwarder#191]
2.如果某域名匹配多个服务器组，则选择的顺序如下：
   (1) 优先选择不含通配符的匹配项，如果仍然有多条匹配，则选择匹配度最高的那个，
       如果匹配度相同的情况下仍然有多条匹配，则选择最后一个。
       （例如 `ipv6.microsoft.com' 比 `microsoft.com' 对于域名 `teredo.ipv6.microsoft.com' 的匹配度更高）
   (2) 然后选择包含通配符的匹配项，如果有多条匹配，则选择第一个；
————————————————————————————————
请问上面说的(1)是否仅指无通配符的情况？

如果现在设置如下
UDPGroup 1.2.4.8 * on
TCPGroup 8.8.4.4 *.google.com no
对于www.google.com域名，根据(2)，尽管`*.google.com`比`*`更匹配，但是仍然走的1.2.4.8，对吧？

一般情况下都是 UDPGroup 设置本地isp dns 然后默认全局`*`域名
而一小部分被污染的域名走tcpgroup，但是这部分域名设置时也会使用通配符`*`
按目前设置就需要调换一下UDPGroup和TCPGroup之间的顺序。
所以，建议默认配置文件中把TCPGroup组放在UDPGroup前面。

另外，”包含通配符的匹配项“中匹配项的意思是指对服务器组中<DOMAIN1,DOMAIN2,...>整体还是其中一个域名说的？
比如
UDPGroup 1.2.4.8 *,github.com on
TCPGroup 8.8.4.4 github.com no
域名github.com，这个匹配项是把`*,github.com`作为一个整体还是`*`和`github.com`都是一个单独的匹配项？
“优先选择不含通配符的匹配项”，是选择的1.2.4.8后面的github.com，还是8.8.4.4后面的github.com？
应该是单独匹配的吧，上面设置，最后github.com走的是哪个？

**Comment by holmium** [comment]
(1)是仅指无通配符的情况。

”包含通配符的匹配项“中匹配项的意思是指对服务器组中<DOMAIN1,DOMAIN2,...>其中一个域名说的。
