### ISSUE TITLE
请教一个域名的解析问题

### ISSUE THREAD

**Issue by liuxb** [holmium/dnsforwarder#192]
一个域名：`m-footmarks.blogspot.com`，会跳转到`m-footmarks.blogspot.co.uk`。
我使用dnsforwarder 6.1.1，设置如下，并保持顺序：
`TCPGroup 208.67.220.220 *.blogspot.*,*blogspot*,*.blogspot.*.* no`
`UDPGroup 114.114.114.114 *,translate.google.cn off`
希望使用tcp协议到208.67.220.220解析，114会污染。
但是结果如下：

cmd中命令：
`C:\Program Files\DNSForwarder>nslookup m-footmarks.blogspot.com
Server:  UnKnown
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out`

dnsforwarder 日志：

`C:\Program Files\DNSForwarder>dnsforwarder.exe
DNSforwarder mainly by holmium. Version 6.1.11 . License : GPL v3.
Time of compilation : Mar 19 2017 13:33:21.

Configure File : C:\Program Files\DNSForwarder\dnsforwarder.config

Jun 17 17:09:07 [INFO] New session.
Jun 17 17:09:07 [INFO] UDP interface 127.0.0.1:53 opened.
Jun 17 17:09:07 [INFO] Disabled domains initialized.
Jun 17 17:09:07 [INFO] Disabled types initialized.
Jun 17 17:09:07 [INFO] Disabled list initialized.
Jun 17 17:09:07 [INFO] Loading Appendhosts completed.
Jun 17 17:09:07 [INFO] Server groups initialized.
Jun 17 17:09:21 [U][127.0.0.1][Domain pointer][1.0.0.127.in-addr.arpa] : 75 bytes
   (SOA)primary name server:127.in-addr.arpa
   (SOA)responsible mail addr:
   (SOA)serial:0
   (SOA)refresh:28800
   (SOA)retry:7200
   (SOA)expire:604800
   (SOA)default TTL:86400
Jun 17 17:09:21 [INFO] Connecting to server ...
Jun 17 17:09:21 [INFO] TCP connection to server established. Time consumed : 297ms
Jun 17 17:09:21 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:21 [INFO] TCP server closed the connection.
Jun 17 17:09:21 [INFO] TCP query retrying...
Jun 17 17:09:21 [INFO] Connecting to server ...
Jun 17 17:09:22 [INFO] TCP connection to server established. Time consumed : 281ms
Jun 17 17:09:22 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:22 [INFO] TCP server closed the connection.
Jun 17 17:09:23 [INFO] Connecting to server ...
Jun 17 17:09:23 [INFO] TCP connection to server established. Time consumed : 297ms
Jun 17 17:09:23 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:23 [INFO] TCP server closed the connection.
Jun 17 17:09:23 [INFO] TCP query retrying...
Jun 17 17:09:23 [INFO] Connecting to server ...
Jun 17 17:09:24 [INFO] TCP connection to server established. Time consumed : 297ms
Jun 17 17:09:24 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:24 [INFO] TCP server closed the connection.
Jun 17 17:09:25 [INFO] Connecting to server ...
Jun 17 17:09:25 [INFO] TCP connection to server established. Time consumed : 281ms
Jun 17 17:09:25 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:25 [INFO] TCP server closed the connection.
Jun 17 17:09:25 [INFO] TCP query retrying...
Jun 17 17:09:25 [INFO] Connecting to server ...
Jun 17 17:09:26 [INFO] TCP connection to server established. Time consumed : 281ms
Jun 17 17:09:26 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:26 [INFO] TCP server closed the connection.
Jun 17 17:09:27 [INFO] Connecting to server ...
Jun 17 17:09:27 [INFO] TCP connection to server established. Time consumed : 297ms
Jun 17 17:09:27 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:27 [INFO] TCP server closed the connection.
Jun 17 17:09:27 [INFO] TCP query retrying...
Jun 17 17:09:27 [INFO] Connecting to server ...
Jun 17 17:09:28 [INFO] TCP connection to server established. Time consumed : 297ms
Jun 17 17:09:28 [ERROR] Receiving from TCP server or proxy failed : 10054 : An existing connection was forcibly closed by the remote host.

Jun 17 17:09:28 [INFO] TCP server closed the connection.
Jun 17 17:09:33 [T][127.0.0.1][IPv4 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv4 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv6 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv6 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv4 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv4 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv6 Address][m-footmarks.blogspot.com] Timed out.
Jun 17 17:09:33 [T][127.0.0.1][IPv6 Address][m-footmarks.blogspot.com] Timed out.`
 
直接使用
nslookup m-footmarks.blogspot.com 208.67.220.220
nslookup -v m-footmarks.blogspot.com 208.67.220.220
是没有问题的。

请问下，怎么办？

**Comment by holmium** [comment]
链接被重置

**Comment by liuxb** [comment]
`链接被重置`的意思是墙在起作用？

那除了设置`AppendHosts 172.217.24.1 m-footmarks.blogspot.com`或`AppendHosts 172.217.24.1 *.blogspot.com`，有别的什么办法吗？

另外，顺便提个请求，`AppendHosts @@`的写法最好可以支持多个域名。就是`AppendHosts @@ domain1,domain2,domain2`这样。

**Comment by holmium** [comment]
是墙的作用
