### ISSUE TITLE
路由器外网断开重连后解析超时

### ISSUE THREAD

**Issue by Suwipe** [holmium/dnsforwarder#193]
使用中发现因为宽带运营商每47小时自动断网一次，断开后路由器会再20秒内重新拨号联网，在这期间如果我的电脑正在使用中，会出来即使路由器重新拨号了，dnsforwarder解析仍然是超时，打开任务管理器结束dnsforwarder进程再启动马上就能用，因为一直是无窗口模式运行，也没启用日志，所以不知道日志输出是怎样的

**Comment by holmium** [comment]
没启用日志如何知道超时？

**Comment by Suwipe** [comment]
发现网页打不开后用nslookup查询解析域名提示超时DNS request timed out.
反正不是第一次出现了，可以试试开启日志输出等下次运营商断网重连的时候就能重现

**Comment by Suwipe** [comment]
手动断开路由器外网重连，一样能重现
日志输出是这样，是否需要提供配置文件
这日志感觉没啥用，就是超时，又没出现什么错误提示
Jul 06 18:37:41 [INFO] New session.
Jul 06 18:37:41 [INFO] Running on daemon mode.
Jul 06 18:37:41 [INFO] UDP interface 0.0.0.0:53 opened.
Jul 06 18:37:41 [INFO] Disabled domains initialized.
Jul 06 18:37:41 [INFO] Disabled types initialized.
Jul 06 18:37:41 [INFO] Disabled list initialized.
Jul 06 18:37:41 [INFO] Server groups initialized.
Jul 06 18:38:20 [U][192.168.1.246][Domain pointer][246.1.168.192.in-addr.arpa] : 103 bytes
   (SOA)primary name server:localhost
   (SOA)responsible mail addr:nobody.invalid
   (SOA)serial:1
   (SOA)refresh:3600
   (SOA)retry:1200
   (SOA)expire:604800
   (SOA)default TTL:10800
Jul 06 18:38:20 [U][192.168.1.246][IPv4 Address][www.qq.com] : 76 bytes
   IPv4 Address:14.17.42.40
   IPv4 Address:14.17.32.211
   IPv4 Address:59.37.96.63
Jul 06 18:38:20 [U][192.168.1.246][IPv6 Address][www.qq.com] : 56 bytes
   IPv6 Address:240e:e1:8100:28:0:0:2:16
Jul 06 18:38:41 [U][192.168.1.246][Domain pointer][246.1.168.192.in-addr.arpa] Timed out.
Jul 06 18:38:51 [U][192.168.1.246][IPv4 Address][www.qq.com] Timed out.
Jul 06 18:38:51 [U][192.168.1.246][IPv6 Address][www.qq.com] Timed out.
Jul 06 18:38:51 [U][192.168.1.246][IPv4 Address][www.qq.com] Timed out.
Jul 06 18:38:51 [U][192.168.1.246][IPv6 Address][www.qq.com] Timed out.
Jul 06 18:39:21 [U][192.168.1.246][Domain pointer][246.1.168.192.in-addr.arpa] Timed out.
Jul 06 18:39:21 [U][192.168.1.246][IPv4 Address][www.qq.com] Timed out.
Jul 06 18:39:21 [U][192.168.1.246][IPv6 Address][www.qq.com] Timed out.
Jul 06 18:39:21 [U][192.168.1.246][IPv4 Address][www.qq.com] Timed out.
Jul 06 18:39:31 [U][192.168.1.246][IPv6 Address][www.qq.com] Timed out.
Jul 06 18:39:41 [U][192.168.1.246][Domain pointer][246.1.168.192.in-addr.arpa] Timed out.
Jul 06 18:39:41 [U][192.168.1.246][IPv4 Address][www.qq.com] Timed out.
Jul 06 18:39:41 [U][192.168.1.246][IPv6 Address][www.qq.com] Timed out.
Jul 06 18:39:41 [U][192.168.1.246][IPv4 Address][www.qq.com] Timed out.
Jul 06 18:39:41 [U][192.168.1.246][IPv6 Address][www.qq.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][dns.msftncsi.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][client.wns.windows.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][client.wns.windows.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][client.wns.windows.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][client.wns.windows.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][dns.msftncsi.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][dns.msftncsi.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][dns.msftncsi.com] Timed out.
Jul 06 18:39:51 [U][192.168.1.246][IPv4 Address][server50002.teamviewer.com] Timed out.

**Comment by holmium** [comment]
知道了

**Comment by holmium** [comment]
6_dev分支最新的应该已经解决了。

**Comment by Suwipe** [comment]
测试可用，解决
