### ISSUE TITLE
6版本发现大量墙内域名解析时会走TCP解析，由于土啬干扰TCP导致经常卡

### ISSUE THREAD

**Issue by zsbstephen** [holmium/dnsforwarder#198]
6版本设了block ip，并且将gfwlist提取的域名加入TCPGroup之中，TCP  server都是设了非53端口的opendns服务器。UDP Server设置了三大运营商和114、阿里的常见DNS。
gfw伪造IP来自这个清单：
https://github.com/shadowsocks/ChinaDNS/blob/master/iplist.txt
打开墙内网页的时候发现不时会卡在查询DNS，打开程序窗口可以看到不停走TCP反复连接服务器但不停被gfw TCP reset导致无法获取IP，但这些墙内的网站的IP其实并不在block ip清单之中。
个人推测，是否是因为目前程序只能同时处理一个DNS查询请求，若TCP查询遇到土啬干扰反复重置和重连的时候，UDP查询会暂时hold住，等TCP查询成功或者超时后才会进行查询？
第一次在github发issues，还不会上传配置文件，请见谅。希望能尽早支持dnscript或者dns2socks等加密查询功能。最后感谢作者几年一直以来的努力，从google ip被全面封杀开始就一直在用了。

**Comment by holmium** [comment]
还是传一下配置文件吧。

其它问题：
目前程序可以同时处理多个查询请求，不管TCP还是UDP。
需要dnscript的话，再套一层dnscript不就可以了嘛，没必要再造一套轮子。

**Comment by zsbstephen** [comment]
感谢回复。原来github直接往浏览器窗口里面拖文件就行。配置文件和TCP、UDP服务器列表都打包了。
[dnsforwarder.zip](https://github.com/holmium/dnsforwarder/files/1234719/dnsforwarder.zip)
奈何软件和编程都还给老师了……，当初第一次用都是搞了很久才搞明白配置文件……所以才会希望把这些TCP加密都集成进来。

**Comment by holmium** [comment]
UDPGroup.txt 改成以下内容：

```
# 井号后面写注释
protocol udp    # 指定协议为 UDP
# 这里写服务器地址
server 114.114.114.114,114.114.114.115,202.96.128.86,202.96.128.166,202.96.134.33,202.96.128.68,223.6.6.6,223.5.5.5,42.120.21.30,112.124.47.27,114.215.126.16,101.226.4.6,218.30.118.6,1.2.4.8,210.2.4.8,123.125.81.6,140.207.198.6,210.21.196.6,221.5.88.88

parallel on    # 是否开启并发查询，“on” 或者 “off”

# 以下是域名，一行一个

* 		# HERE !!!!!!!!!!!!!!!!!!!!!
```

**Comment by zsbstephen** [comment]
感谢回复。已经在UDPGroup.txt里面添加了*这一行列，不过问题依然存在。试了一下，将TCPGroup.txt删掉了可以治标不治本解决。

**Comment by holmium** [comment]
哪个问题依然存在？TCP查询现在已经废了，怎么改都不会有效的。

**Comment by zsbstephen** [comment]
就是UPD查墙内域名的时候会卡。TCP明文查询现在的确是基本废了，TCP走非53端口一样给你重置。
