### ISSUE TITLE
linux下启动失败

### ISSUE THREAD

**Issue by horizonl** [holmium/dnsforwarder#204]
按wiki编译后安装，使用root权限开会提示Segmentation fault (core dumped)，使用普通用户开提示权限不够/Permission denied

**Comment by holmium** [comment]
dnsforwarder -p 执行后是什么结果？

**Comment by horizonl** [comment]
刚试了下改成英文的配置文件用root权限跑起来了，可能是配置文件编码格式问题。普通用户还是无法开启应该是权限不允许。

**Comment by holmium** [comment]
普通用户当然没有权限，开启53端口必须是root
