### ISSUE TITLE
Disabledlist 不能正常工作？

### ISSUE THREAD

**Issue by yygcom** [holmium/dnsforwarder#206]
文件格式每行一个域名或者域名前面加了DisabledDomain 都无法工作，如果是格式错误，麻烦提供一下这个文件的格式，谢谢

**Comment by holmium** [comment]
请先把程序版本、配置文件发上来看看

**Comment by yygcom** [comment]
版本号：
DNSforwarder mainly by holmium. Version 6.1.14 . License : GPL v3.
===================================

config是用的示例文件，修改如下部分
# DisabledList <PATH>
# 从文件载入到禁用列表 (since 5.0.3)
# 写多条 `DisabledList' 可以加载多个文件，路径两头不要加引号
DisabledList /root/.dnsforwarder/Disabledlist.ads.rule
DisabledList /root/.dnsforwarder/Disabledlist.ads.2.rule

===================================
Disabledlist.ads.rule 文件内容
# head -n 10 /root/.dnsforwarder/Disabledlist.ads.rule
*.00oo00.com
*.00pic.com
*.0311fy.net
*.1qtv.com
*.37cs.com
*.4001075656.com
*.45io.com
*.4wad.com
*.51.la
*.520jr.com

Disabledlist.ads.2.rule 文件内容
# head -n 10 /root/.dnsforwarder/Disabledlist.ads.2.rule
DisabledDomain *.2144.cc
DisabledDomain *.2144.cn
DisabledDomain *.2345.com
DisabledDomain *.345.pl
DisabledDomain *.3dwwwgame.com
DisabledDomain *.50bang.org
DisabledDomain *.565882.com
DisabledDomain *.72link.com
DisabledDomain *.9377.com
DisabledDomain *.a3p4.net

**Comment by holmium** [comment]
程序输出贴一下吧

**Comment by yygcom** [comment]
在树莓派上，现在不方便弄，就是如果直接再config文件里面用
DisabledDomain *.565882.com
这种是能起作用，查询的时候直接就是空的ip
但是用Disabledlist加载文件规则时查询直接就出来ip了

**Comment by holmium** [comment]
我没有树莓派，暂时没有办法复现，我自己的电脑上是没问题的

**Comment by yygcom** [comment]
规则文件里面的格式是怎么的呢，是每行一个域名还是需要在域名前面加 DisalbedDomain 呢？

**Comment by holmium** [comment]
是每行一个域名

**Comment by yygcom** [comment]
刚才在一台centos7机器测试，可以了，不知道树莓派上的是怎么回事等空了重新编译试试
