### ISSUE TITLE
刚升级了Windows 10的1709版本，新老版本均无法正常运行。

### ISSUE THREAD

**Issue by simhfc** [holmium/dnsforwarder#207]
双击运行一闪而过，切换到admin命令行显示如下：
v6.1.14:
Nov 25 20:28:19 [ERROR] Opening UDP interface 127.0.0.1:53 failed : 10013 : An attempt was made to access a socket in a way forbidden by its access permissions.

Nov 25 20:28:19 [ERROR] No UDP interface opened.

v5.0.41:
[ERROR] Creating UDP socket failed. 10013 : An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by holmium** [comment]
请先谷歌

**Comment by simhfc** [comment]
可确认是1709版的改进导致，由于微软对新版Hyper-V的虚拟网卡做了改动，默认的Default Switch采用NAT方式工作且无法删除，所以如果在1709版中加装Hyper-V组件后，将导致系统启动时强制运行ICS服务且无法禁止，UDP 0.0.0.0:53端口被它占用，出现10013报错。

目前看来只要是加装了Hyper-V组件的1709版Win10，都只能在手动停止ICS空出端口之后，才能恢复UDP53端口的DNS代理程序，阻断了自动加载，短期内势必影响本项目的易用性，可惜。

**Comment by yoooooooo** [comment]
@simhfc 看起来没有别的办法了？

**Comment by simhfc** [comment]
生产环境的话，除了手动停止外，暂时没想到其他好办法，好在生产环境长期开机，一次操作长期有效；个人应用的话，可换其他VM，简单需求用轻量级的VirtualBox表现不错。
