### ISSUE TITLE
UDP TCP DNS Group 查询顺序的问题

### ISSUE THREAD

**Issue by PantherJohn** [holmium/dnsforwarder#208]
## 不知道能不能这样:
Client: want some "shadowsocks.org" => DNS Forwarder: Alright, 
Asking UDP Group (`UDPGroup 223.5.5.5,223.6.6.6 * on`)
       TCP Group (`TCPGroup 210.87.251.1,210.87.251.2 * no`) `simultaneously`...
Oh, busted! UDP Group returned fake IPs... 
```
BlockIP 243.185.187.39,46.82.174.68,37.61.54.158,93.46.8.89,59.24.3.173,203.98.7.65,8.7.198.45,78.16.49.15,159.106.121.75,243.185.187.39,46.82.174.68,37.61.54.158,93.46.8.89,59.24.3.173,203.98.7.65,8.7.198.45,78.16.49.15,31.13.78.65,159.106.121.75
```
use TCP Group instead.

Client: want some "shadowsocks.org" => DNS Forwarder: Alright, 
Asking UDP Group (`UDPGroup 223.5.5.5,223.6.6.6 * on`)
       TCP Group (`TCPGroup 210.87.251.1,210.87.251.2 * no`) `simultaneously`...
UDP Group did not return fake IPs... 
Combine these results with that returned by TCP ones.

## My Configuration
```
UDPGroup 223.5.5.5,223.6.6.6 * on
TCPGroup 210.87.251.1,210.87.251.2 * no
BlockIP 243.185.187.39,46.82.174.68,37.61.54.158,93.46.8.89,59.24.3.173,203.98.7.65,8.7.198.45,78.16.49.15,159.106.121.75,243.185.187.39,46.82.174.68,37.61.54.158,93.46.8.89,59.24.3.173,203.98.7.65,8.7.198.45,78.16.49.15,31.13.78.65,159.106.121.75
```

## Expectations
UDP & TCP Group query simultaneously; filter results with `BlockIP` statement after receiving responses.

## What I see now
客户端请求shadowsocks.org no response
`connection timed out; no servers could be reached`
查询UDP后收到Fake IPs没有再查询TCP Group

**Comment by PantherJohn** [comment]
It seems that ip bad response filter no longer works. WHAT WE CAN DO IS ONCE RECEIVING BUSTED IPs WE SHIFT OUR QUERY TO TCP DNS SERVERS through a SOCKS5 tunnel in case the TCP response will not be affected either

**Comment by holmium** [comment]
It has been the case for a long time, that a real ip doesn't follow a fake ip.
