### ISSUE TITLE
6版本在ubuntu16.04下编译后不能运行，5版本可以这是为什么？

### ISSUE THREAD

**Issue by JunShine** [holmium/dnsforwarder#209]
ubuntu16.04编译6版本也没看到提示出错，有编译后的dnsforwarder文件，但是运行起来提示
dnsforearder：未找到命令
切换5版本，同样编译后却没问题

**Comment by holmium** [comment]
有install吗？是不是输错了

**Comment by JunShine** [comment]
有make install呢
root@ubuntu:~ /dnsforwarder# . /configure --enable-downloader=wget
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
.......
checking for uint32_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating makefile
config.status: creating config.h
config.status: executing depfiles commands

root@ubuntu:~ /dnsforwarder# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/dnsforwarder/missing aclocal-1.15
 cd . && /bin/bash /root/dnsforwarder/missing automake-1.15 --gnu
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/dnsforwarder/missing autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --enable-downloader=wget --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for log in -lm... yes
checking for sqrt in -lm... yes
checking for pow... yes
checking for sqrt... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking wordexp.h usability... yes
checking wordexp.h presence... yes
checking for wordexp.h... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for setenv... yes
checking for wordexp... yes
checking for setenv... (cached) yes
checking for wordexp... (cached) yes
checking for clock_gettime... yes
checking for inet_ntoa... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for select... yes
checking for socket... yes
checking for strchr... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strstr... yes
checking for pid_t... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for size_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/dnsforwarder/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-am
make[1]: Entering directory '/root/dnsforwarder'
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT addresslist.o -MD -MP -MF .deps/addresslist.Tpo -c -o addresslist.o addresslist.c
mv -f .deps/addresslist.Tpo .deps/addresslist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT dynamichosts.o -MD -MP -MF .deps/dynamichosts.Tpo -c -o dynamichosts.o dynamichosts.c
mv -f .deps/dynamichosts.Tpo .deps/dynamichosts.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT array.o -MD -MP -MF .deps/array.Tpo -c -o array.o array.c
mv -f .deps/array.Tpo .deps/array.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT mcontext.o -MD -MP -MF .deps/mcontext.Tpo -c -o mcontext.o mcontext.c
mv -f .deps/mcontext.Tpo .deps/mcontext.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT filter.o -MD -MP -MF .deps/filter.Tpo -c -o filter.o filter.c
mv -f .deps/filter.Tpo .deps/filter.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT stablebuffer.o -MD -MP -MF .deps/stablebuffer.Tpo -c -o stablebuffer.o stablebuffer.c
mv -f .deps/stablebuffer.Tpo .deps/stablebuffer.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT bst.o -MD -MP -MF .deps/bst.Tpo -c -o bst.o bst.c
mv -f .deps/bst.Tpo .deps/bst.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT mmgr.o -MD -MP -MF .deps/mmgr.Tpo -c -o mmgr.o mmgr.c
mv -f .deps/mmgr.Tpo .deps/mmgr.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT goodiplist.o -MD -MP -MF .deps/goodiplist.Tpo -c -o goodiplist.o goodiplist.c
mv -f .deps/goodiplist.Tpo .deps/goodiplist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT statichosts.o -MD -MP -MF .deps/statichosts.Tpo -c -o statichosts.o statichosts.c
mv -f .deps/statichosts.Tpo .deps/statichosts.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT cacheht.o -MD -MP -MF .deps/cacheht.Tpo -c -o cacheht.o cacheht.c
mv -f .deps/cacheht.Tpo .deps/cacheht.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT hcontext.o -MD -MP -MF .deps/hcontext.Tpo -c -o hcontext.o hcontext.c
mv -f .deps/hcontext.Tpo .deps/hcontext.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT pipes.o -MD -MP -MF .deps/pipes.Tpo -c -o pipes.o pipes.c
mv -f .deps/pipes.Tpo .deps/pipes.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT stringchunk.o -MD -MP -MF .deps/stringchunk.Tpo -c -o stringchunk.o stringchunk.c
mv -f .deps/stringchunk.Tpo .deps/stringchunk.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT cachettlcrtl.o -MD -MP -MF .deps/cachettlcrtl.Tpo -c -o cachettlcrtl.o cachettlcrtl.c
mv -f .deps/cachettlcrtl.Tpo .deps/cachettlcrtl.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT hosts.o -MD -MP -MF .deps/hosts.Tpo -c -o hosts.o hosts.c
mv -f .deps/hosts.Tpo .deps/hosts.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT ptimer.o -MD -MP -MF .deps/ptimer.Tpo -c -o ptimer.o ptimer.c
mv -f .deps/ptimer.Tpo .deps/ptimer.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT stringlist.o -MD -MP -MF .deps/stringlist.Tpo -c -o stringlist.o stringlist.c
mv -f .deps/stringlist.Tpo .deps/stringlist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT hostscontainer.o -MD -MP -MF .deps/hostscontainer.Tpo -c -o hostscontainer.o hostscontainer.c
mv -f .deps/hostscontainer.Tpo .deps/hostscontainer.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT tcpm.o -MD -MP -MF .deps/tcpm.Tpo -c -o tcpm.o tcpm.c
mv -f .deps/tcpm.Tpo .deps/tcpm.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT dnscache.o -MD -MP -MF .deps/dnscache.Tpo -c -o dnscache.o dnscache.c
mv -f .deps/dnscache.Tpo .deps/dnscache.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT hostsutils.o -MD -MP -MF .deps/hostsutils.Tpo -c -o hostsutils.o hostsutils.c
mv -f .deps/hostsutils.Tpo .deps/hostsutils.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT readconfig.o -MD -MP -MF .deps/readconfig.Tpo -c -o readconfig.o readconfig.c
mv -f .deps/readconfig.Tpo .deps/readconfig.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT timedtask.o -MD -MP -MF .deps/timedtask.Tpo -c -o timedtask.o timedtask.c
mv -f .deps/timedtask.Tpo .deps/timedtask.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT dnsgenerator.o -MD -MP -MF .deps/dnsgenerator.Tpo -c -o dnsgenerator.o dnsgenerator.c
mv -f .deps/dnsgenerator.Tpo .deps/dnsgenerator.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT iheader.o -MD -MP -MF .deps/iheader.Tpo -c -o iheader.o iheader.c
mv -f .deps/iheader.Tpo .deps/iheader.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT readline.o -MD -MP -MF .deps/readline.Tpo -c -o readline.o readline.c
mv -f .deps/readline.Tpo .deps/readline.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT udpfrontend.o -MD -MP -MF .deps/udpfrontend.Tpo -c -o udpfrontend.o udpfrontend.c
mv -f .deps/udpfrontend.Tpo .deps/udpfrontend.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT dnsparser.o -MD -MP -MF .deps/dnsparser.Tpo -c -o dnsparser.o dnsparser.c
mv -f .deps/dnsparser.Tpo .deps/dnsparser.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT ipchunk.o -MD -MP -MF .deps/ipchunk.Tpo -c -o ipchunk.o ipchunk.c
mv -f .deps/ipchunk.Tpo .deps/ipchunk.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT udpm.o -MD -MP -MF .deps/udpm.Tpo -c -o udpm.o udpm.c
mv -f .deps/udpm.Tpo .deps/udpm.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT dnsrelated.o -MD -MP -MF .deps/dnsrelated.Tpo -c -o dnsrelated.o dnsrelated.c
mv -f .deps/dnsrelated.Tpo .deps/dnsrelated.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT ipmisc.o -MD -MP -MF .deps/ipmisc.Tpo -c -o ipmisc.o ipmisc.c
mv -f .deps/ipmisc.Tpo .deps/ipmisc.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT simpleht.o -MD -MP -MF .deps/simpleht.Tpo -c -o simpleht.o simpleht.c
mv -f .deps/simpleht.Tpo .deps/simpleht.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT utils.o -MD -MP -MF .deps/utils.Tpo -c -o utils.o utils.c
utils.c: In function ‘GetModulePath’:
utils.c:129:2: warning: #warning Implement this [-Wcpp]
 #warning Implement this
  ^
mv -f .deps/utils.Tpo .deps/utils.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT domainstatistic.o -MD -MP -MF .deps/domainstatistic.Tpo -c -o domainstatistic.o domainstatistic.c
mv -f .deps/domainstatistic.Tpo .deps/domainstatistic.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT linkedqueue.o -MD -MP -MF .deps/linkedqueue.Tpo -c -o linkedqueue.o linkedqueue.c
mv -f .deps/linkedqueue.Tpo .deps/linkedqueue.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT socketpool.o -MD -MP -MF .deps/socketpool.Tpo -c -o socketpool.o socketpool.c
mv -f .deps/socketpool.Tpo .deps/socketpool.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT winmsgque.o -MD -MP -MF .deps/winmsgque.Tpo -c -o winmsgque.o winmsgque.c
mv -f .deps/winmsgque.Tpo .deps/winmsgque.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT downloader.o -MD -MP -MF .deps/downloader.Tpo -c -o downloader.o downloader.c
mv -f .deps/downloader.Tpo .deps/downloader.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT logs.o -MD -MP -MF .deps/logs.Tpo -c -o logs.o logs.c
mv -f .deps/logs.Tpo .deps/logs.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_WGET  -MT socketpuller.o -MD -MP -MF .deps/socketpuller.Tpo -c -o socketpuller.o socketpuller.c
mv -f .deps/socketpuller.Tpo .deps/socketpuller.Po
gcc  -pthread  -DDOWNLOAD_WGET   -pthread  -o dnsforwarder addresslist.o dynamichosts.o main.o array.o mcontext.o filter.o stablebuffer.o bst.o mmgr.o goodiplist.o statichosts.o cacheht.o hcontext.o pipes.o stringchunk.o cachettlcrtl.o hosts.o ptimer.o stringlist.o hostscontainer.o tcpm.o dnscache.o hostsutils.o readconfig.o timedtask.o dnsgenerator.o iheader.o readline.o udpfrontend.o dnsparser.o ipchunk.o udpm.o dnsrelated.o ipmisc.o simpleht.o utils.o domainstatistic.o linkedqueue.o socketpool.o winmsgque.o downloader.o logs.o socketpuller.o  -lm -lm
make[1]: Leaving directory '/root/dnsforwarder'

root@ubuntu:~/dnsforwarder# make install
make[1]: Entering directory '/root/dnsforwarder'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c dnsforwarder '/usr/local/bin'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/root/dnsforwarder'

root@ubuntu:~ /dnsforwarder# cd /usr/local/bin

root@ubuntu: /usr/local/bin# ls
dnsforwarder

root@ubuntu: /usr/local/bin# dnsforearder -h
dnsforearder：未找到命令

**Comment by holmium** [comment]
/usr/bin/install -c dnsforwarder '/usr/local/bin'

看起来是放在/usr/local/bin里了，看看/usr/local/bin有没有在path中？或者dnsforwarder有没有可执行权限

**Comment by JunShine** [comment]
/usr/local/bin在path中了，也有可执行权限的。恩，算了哈，我用5版本也可以了哈
