### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by yiguihai** [holmium/dnsforwarder#211]
make  all-am
make[1]: Entering directory '/data/data/com.termux/files/home/dnsforwarder'
gcc -DHAVE_CONFIG_H -I.     -pthread  -static  -MT downloader.o -MD -MP -MF .deps/downloader.Tpo -c -o downloader.o downloader.c
In file included from downloader.c:28:
./downloader.h:14:11: error: unknown type name 'BOOL'
  ...BOOL                       Append,
     ^
1 error generated.
make[1]: *** [makefile:438: downloader.o] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/dnsforwarder'
make: *** [makefile:288: all] Error 2

**Comment by holmium** [comment]
试试新的dev分支？
