### ISSUE TITLE
DisabledList 能否定时刷新呢

### ISSUE THREAD

**Issue by lifenjoiner** [holmium/dnsforwarder#215]
背景：
由一封钓鱼邮件，挖到一个恶意域名[*.erlivia.ltd系列](https://www.virustotal.com/#/domain/i876edw4e5f6tg78hy9tg7r6ftgiy8.erlivia.ltd)，以及一个不错的资源[malwaredomains](https://www.malwaredomains.com/?page_id=66)（有[justdomains](https://mirror1.malwaredomains.com/files/justdomains)可用，更新“及时”）。遂想利用一下……

问题：
比如这个[*.erlivia.ltd系列](https://www.virustotal.com/#/domain/i876edw4e5f6tg78hy9tg7r6ftgiy8.erlivia.ltd)，里面是以`erlivia.ltd`表示的。
又没有找到对应的`host`文件，就只能用`DisabledList`了。
搜索了一下，好像是不支持`DisabledList`定时刷新的……
https://github.com/holmium/dnsforwarder/search?utf8=%E2%9C%93&q=TimedTask_Add&type=

所以，请教一下，能否定时刷新呢？如果不支持，有什么好办法吗？或者能否增强一下呢？
还有顺带问一下，如果其它相关配置文件（比如GroupFile）更新了，是否必需重启dnsforwarder呢？

**Comment by holmium** [comment]
是要重启生效。

还不如写个定时脚本定时重启dnsforwarder。

**Comment by lifenjoiner** [comment]
好吧，了解……

重启的问题是服务有中断。
我是在windows下单机使用的，DNS设置是在自动获得的Servers前面加`127.0.0.1`。发现，重启之后有些程序的查询就不走首选而走备选了……
我把更新命令写在了HostsScript里，方便的时候手动重启凑合吧~

**Comment by holmium** [comment]
中断也就不到1秒钟，又是单机使用，难道自动更新不是伪需求？

我觉得就算1个月更新一次对实际使用也没有什么影响。

另外搞个自动更新这中间出bug的可能性也很高，而且对程序性能也会有一定影响。

**Comment by lifenjoiner** [comment]
你误会啦，是说重新加载我自己更新过的`DisabledList`文件

**Comment by lifenjoiner** [comment]
回来看看，也不知道怎么火就拱起来了啊~
算了，都不必在意。咱也没什么不文明行为。我起初也就是来确认一下程序有哪些功能没有哪些功能。至于“增强”的说法，也就是个期望，并不是“绑架”。也从来没有觉得有权利要求您做什么。你的程序对我有用，已经很感谢啦！
Issue 我就关掉了。
