### ISSUE TITLE
做为chinadns的前端好像会超时

### ISSUE THREAD

**Issue by wendellou** [holmium/dnsforwarder#216]
直接dig www.google.com -p 5353 @127.0.0.1  # dnsforwarder 监听端口
能正确返回

把127.0.0.1:5353 配置到chinadns后，

dig www.google.com -p 53 @127.0.0.1  # chinadns监听端口

无法正确返回，换成ss-tunnel可以

**Comment by holmium** [comment]
配置和输出贴一下？
