### ISSUE TITLE
disabledomain 能否直接返回空记录

### ISSUE THREAD

**Issue by MonwF** [holmium/dnsforwarder#219]
现在查询是丢包还是啥，虽然会生效，但会卡到超时，而非立即返回

**Comment by holmium** [comment]
disabledomain是直接返回空记录

**Comment by holmium** [comment]
其它的最好给出配置文件和程序输出吧

**Comment by MonwF** [comment]
不好意思，昨晚表述错误，应该是`DisabledType`，但今天早上验证了下又可以了

**Comment by holmium** [comment]
哦，DisabledType也是直接返回空记录。

可能有些程序会忽略空记录的dns，转而向备选dns查询。
