### ISSUE TITLE
Feature Request: 支持载入两个（或多个）GfwList

### ISSUE THREAD

**Issue by Firef0x** [holmium/dnsforwarder#23]
我把多年积累的`AutoProxy`自定义规则做成了`GfwList`格式，放到了网上。希望本程序能支持载入两个（或多个）`GfwList`，省去手工转换的麻烦。

**Comment by Firef0x** [comment]
很遗憾作者不准备实现此功能了，不过以目前的网络情况，自己增补的规则见光死得很快，似乎这个特性请求也没有特别大的意义了。还是非常感谢作者伟大的贡献！ :rose: 如果关闭问题时能够顺便解释下原因就更好了。 :pray:

**Comment by holmium** [comment]
谢谢
