### ISSUE TITLE
Bug Report: "[ERROR]  !!!!! Something bad happend, please restert this program."

### ISSUE THREAD

**Issue by zhaosistu2** [holmium/dnsforwarder#43]
自己在Mac OS X 10.10 x64系统下编译的DNSForwarder 5最新版（2014年10月29日git clone）报告了如标题所示错误，编译过程为在dnsforwarder目录下执行以下命令：make build && cd build && ../configure && make && cp dnsforwarder ~/bin/ && make clean。

运行时的命令为：sudo ~/bin/dnsforwarder，已将dnsforwarder.config复制为/var/root/.dnsforwader/config。

刚开始运行的时候没有问题，运行一段时间后，大概为30分钟左右，出现了标题中的错误，具体的错误提示包括：
[ERROR]
 
 
 
 
 
 
 
  
 
[ERROR]  !!!!! Something bad happend, please restert this program.
[ERROR] Downloading GFW List failed. Waiting 30 second(s) to try again.
[INFO] Loading GFW List From https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt ...

是的，没错，第一个[ERROR]后面是空的，然后接下来有9个空行（github不能显示空行？编辑的时候明明可以看到9个空行。。。），然后是最后面三行，最后卡在那里不动了，Ctrl+C之后重新运行是好好的，然后过了一段时间又卡在那里不动了，并出现上述错误提示。

并且用作者编译的二进制文件运行也会出现这个错误。

请问大神怎么回事？谢谢！

**Comment by holmium** [comment]
这个bug可能已经修复了
