### ISSUE TITLE
对于cname的源域可以指定hosts吗？

### ISSUE THREAD

**Issue by spance** [holmium/dnsforwarder#49]
比如说w.AAA.com 用cname到 x.BBB.net上，dns返回的记录中好像是有x.BBB.net的源域，在这一步查询x.BBB.net有hosts匹配就替换掉返回呢？

其实简单说就是有很多的域名别名到了*.edgecastcdn.net ghs.google.com等等，别名后的新域名就会无数多，很难做完整的hosts，所以就想看源域有匹配就替换掉。
我对dns协议报文不了解，不知道这个想法合适否。

**Comment by holmium** [comment]
这个以后应该会实现

**Comment by spance** [comment]
多谢。顺祝元旦狠狠的快乐。
