### ISSUE TITLE
dnsforwarder停止运行

### ISSUE THREAD

**Issue by alexwhen** [holmium/dnsforwarder#50]
[INFO] TCP server closed the connection.
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : -1.1000000s
[INFO] TCP connection to TCP server established. Time consumed : -1.1000000s
[ERROR] Sending to TCP server failed (1) : 32 : Broken pipe
[INFO] TCP server closed the connection.
连续几次后就死掉了

**Comment by litrue** [comment]
我是在osx上编译的，windows上没试

**Comment by Explorare** [comment]
同样的问题，今天遇到的，如果关掉goagent，只是用dnsforwarder,DNS配置为127.0.0.1，hosts文件清空，已刷新dns缓存，本软件执行50行左右就挂了，没有正常连接上https://www.google.com/，其他网站也连不上。该项目目前是否还存活？

**Comment by holmium** [comment]
这个问题应该已经解决
