### ISSUE TITLE
Windows版本能注册为系统服务吗?

### ISSUE THREAD

**Issue by logtee** [holmium/dnsforwarder#51]
Windows版本能注册为系统服务吗?
这样就不用每次开机都打开软件了.

**Comment by yellowvii** [comment]
我使用的是 SrvanyUI 
地址: http://wangye.org/blog/archives/644/

**Comment by 476210180** [comment]
@yellowvii 
感谢楼上，找了这个工具好久了！
![2015-01-03_194014](https://cloud.githubusercontent.com/assets/8447650/5602341/bb445028-9381-11e4-96b2-d022d272ad8a.png)

**Comment by yellowvii** [comment]
不客气，能帮到你我也高兴。
2015年1月3日 下午7:50于 "476210180" <notifications@github.com>写道：
