### ISSUE TITLE
无法加载 GfwList

### ISSUE THREAD

**Issue by LiamHuang0205** [holmium/dnsforwarder#52]
1. 无法加载位于 Google Code 上的 gfwlist.txt，猜测可能是被拦截了；
2. 将文件下载到本地，选项 GfwList ./gfwlist.txt，提示下载失败；
3. 将文件传到自己的服务器上（墙内），选项 GfwList http://domain/path/to/gfwlist.txt，提示下载失败。

Sys info:

Mac OS X 10.9.5
dnsforwarder 5

**Comment by 476210180** [comment]
gfwlist选项只支持通过http协议载入gfwlist，也就是说如果从本地载入的话起码要建立服务器，比如Windows下安装IIS，至于Mac我就不懂了……
另外GoogleCode确实已经大部被封
从墙内服务器载入请别忘了墙内就是ZF的地盘了……

**Comment by spance** [comment]
整个自己常用hosts也就几十行而已，何必用那个大墙list那么大的，分运营商分地区大墙效果皆不同，大而全往往不如小而精。在不行就下回来当成本地hosts配进去。

**Comment by holmium** [comment]
不是有ExcludedList选项吗？
