### ISSUE TITLE
default.config 默认编码问题

### ISSUE THREAD

**Issue by yfdyh000** [holmium/dnsforwarder#53]
我在 Firefox 中访问 https://raw.githubusercontent.com/holmium/dnsforwarder/master/default.config 会得到乱码的页面，虽然另存为后打开是正常的。HTTP响应头中有 Content-Type:"text/plain; charset=utf-8"，而这个文件好像是用GBK/GB2312编码的。为什么这文件没有用更通用的UTF-8呢。

**Comment by 476210180** [comment]
响应头有UTF-8应该是国外网站都会选用这种几乎什么字符都能显示的编码方案。
