### ISSUE TITLE
在Mac OS X中能否无需root权限即可监听端口？

### ISSUE THREAD

**Issue by zky999** [holmium/dnsforwarder#57]
因为在Mac OS X 10.10中dnsforwarder 5.0.14经常会自动退出，所以我目前的解决方法是自己写了个脚本，让dnsforwarder在死循环中运行，自动退出了会重新运行，terminal的窗口一直开着，并且中脚本中trap了SIGTERM等信号来监听Ctrl+C等事件，倒也用着还行，算是在目前holmium没有时间来解决dnsforwarder崩溃问题的情况下的折衷办法，这个办法在Windows下的Cygwin中也运行良好，因为在Cygwin中无需sudo来运行dnsfowarder，所以每次崩溃重启会自动运行创建端口，但是Mac下就不行了，因为崩溃重启再次运行 sudo dnsfowarder的时候需要输入密码，卡在那里了，所以我想问下holmium对于这个问题有没有什么解决办法？能否无需root权限即可运行dnsforwarder？我试过，不用root权限运行dnsforwarder则会提示"[ERROR] Creating UDP socket failed. 13 : Permission denied".

示例bash脚本：
```
#!/usr/bin/env bash
trap 'run_again=0' SIGINT SIGTERM
run_again=1
while [[ ${run_again} -eq 1 ]]; do
    sudo dnsforwarder # 此处需要输入密码，在dnsforwarder崩溃之后不能自动重启。
done
```

**Comment by tofuliang** [comment]
有没有试过用 sudo 来执行执行这个脚本,而不是在脚本里用 sudo 运行dnsforwarder ?

在 2015年2月2日 上午11:43，zky999 <notifications@github.com>写道：

**Comment by zky999** [comment]
感谢回复！

您建议的方案应该是可行的，因为如果用root权限运行那个脚本的话，那么该脚本中的所有程序都运行于该脚本所创建的sub shell中，由于用sudo运行该脚本，所以该sub shell是有root权限的，所以运行到sudo dnsforwarder时也无需输入密码了。

但是这个方案有个安全隐患就是除了dnsforwarder之外，脚本中的其他所有程序都有root权限了，如果脚本写得不完善，很有可能会带来灾难性的后果。

所以在您的启发下，我意识到了既然我考虑的因素包括：一、无需输入密码；二、把root权限仅给需要的程序，那么何不用sudo的/etc/sudoers文件来指定当运行“sudo dnsforwarder”时无需输入密码呢？在终端中输入“sudo visudo”在“\# User privilege specification"那一节下加入"自己的用户名 ALL=(ALL) NOPASSWD: /path/to/dnsforwarder”，则再次运行之前那个脚本的时候，sudo就不会再提示输入自己的密码了，而且dnsforwarder也以root权限运行了。

再次感谢！
