### ISSUE TITLE
对于特定网络环境下的特定网址DNS解析超时

### ISSUE THREAD

**Issue by yyysuo** [holmium/dnsforwarder#58]
现象：第一次访问www.hi-pda.com时经常出现延迟10秒左右的情况，dnsforwarder在10秒后会跳出一堆的time out，然后就可以正常访问了。设置DNS为202.102.152.3时无延迟，

学校局域网内网，外接中国联通100M光纤

主协议是UDP UDP中包含202.102.152.3中国联通的DNS，
指定了
DedicatedServer www.hi-pda.com 202.102.152.3
DedicatedServer www.zygames.com 202.102.152.3

www.hi-pda.com用了反向代理
ping www.hi-pda.com 显示ping hipda.g.zygames.com

**Comment by holmium** [comment]
超时就是超时

**Comment by yyysuo** [comment]
问题在于单用联通DNS是无延迟的，用了包含联通DNS的dnsforwarder却有延迟，不知道是不是我设置的问题，我开启了GFWLIST,主协议是UDP。
