### ISSUE TITLE
最新版mac下编译不通过

### ISSUE THREAD

**Issue by alexwhen** [holmium/dnsforwarder#60]
/Users/alex/dnsforwarder $ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT hosts.o -MD -MP -MF .deps/hosts.Tpo -c -o hosts.o hosts.c
hosts.c:337:9: error: non-void function 'GetAnswersByName' should return a
      value [-Wreturn-type]
        return;
        ^
hosts.c:562:17: warning: assigning to 'char *' from 'const char *' discards
      qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  ...AnswersPos = DNSJumpOverQuestionRecords(DNSResult);
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[1]: *** [hosts.o] Error 1
make: *** [all] Error 2

**Comment by holmium** [comment]
现在的呢？

**Comment by litrue** [comment]
马上更新一下测试

**Comment by litrue** [comment]
成功，谢谢

**Comment by litrue** [comment]
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : 0.0s
[INFO] TCP server closed the connection.
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : 0.0s

**Comment by litrue** [comment]
新版报上面的错，但是可用
