### ISSUE TITLE
5版本TCP查询依然有些问题

### ISSUE THREAD

**Issue by holmium** [holmium/dnsforwarder#61]

**Comment by litrue** [comment]
是的，tcp查询加入代理也同样有问题

**Comment by smovie** [comment]
可否提供全部UDP查询的功能，因为现在TCP也有干扰，而非标准端口的查询UDP和TCP目前都没有干扰，但TCP查询还是有bug，而UDP查询占用资源少速度更快

**Comment by holmium** [comment]
本来就可以全部UDP的

**Comment by litrue** [comment]
UDP干扰得不行了

**Comment by smovie** [comment]
请教下怎么全部用UDP？配置文件里只有TCPServer和UDPServer，然后PrimaryServer指定其中一个。有没有UDPServer1、UDPServer2这样的，然后PrimaryServer指定一个？
