### ISSUE TITLE
5.x的版本tcp查询timeout

### ISSUE THREAD

**Issue by smovie** [holmium/dnsforwarder#64]
用dig查询的话一切正常，但是用nslookup查询很慢，会出现timeout，客户端信息如下：
C:\>nslookup youku.com 127.0.0.1
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  127.0.0.1

非权威应答:
名称:    youku.com
Addresses:  123.126.99.31
          101.227.10.19
          220.181.185.141
          183.61.116.211
          119.167.145.19
          111.13.127.48

服务端信息如下：
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : 16ms
Mar 13 18:12:24 [T][127.0.0.1][IPv4 Address][youku.com] : 123 bytes
   IPv4 Address:119.167.145.19
   IPv4 Address:183.61.116.211
   IPv4 Address:220.181.185.141
   IPv4 Address:101.227.10.19
   IPv4 Address:111.13.127.48
   IPv4 Address:123.126.99.31
[INFO] TCP server closed the connection.
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : 16ms
[INFO] TCP server closed the connection.
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : 0ms
Mar 13 18:12:47 [T][127.0.0.1][IPv4 Address][youku.com] : 123 bytes
   IPv4 Address:123.126.99.31
   IPv4 Address:101.227.10.19
   IPv4 Address:220.181.185.141
   IPv4 Address:183.61.116.211
   IPv4 Address:119.167.145.19
   IPv4 Address:111.13.127.48
[INFO] TCP server closed the connection.
[INFO] Connecting to TCP server ...
[INFO] TCP connection to TCP server established. Time consumed : 16ms
Mar 13 18:12:47 [T][127.0.0.1][IPv6 Address][youku.com] : 78 bytes
   start of authority record:
      primary name server:ns1.youku.com
      responsible mail addr:hostmaster.youku.com
      serial:2007102901
      refresh:3600
      retry:900
      expire:604800
      default TTL:86400
[INFO] TCP server closed the connection.
Mar 13 18:12:57 [T][127.0.0.1][Domain pointer][1.0.0.127.in-addr.arpa] Timed out.

表现在游览器上就是打开网页要比较久，试了IE和firefox都如此。如果用UDP的话就正常。

另外，2.x的版本也没有这个问题。

windows 2003和win7上都是这个结果。

**Comment by binque** [comment]
我也是一样的错误。好多的timeout啊 咋整。
Mar 17 09:43:56 [T][127.0.0.1][IPv6 Address][github.com] Timed out.
Mar 17 09:43:56 [T][127.0.0.1][IPv4 Address][github.com] Timed out.
Mar 17 09:43:56 [T][127.0.0.1][IPv6 Address][github.com] Timed out.
Mar 17 09:43:56 [T][127.0.0.1][IPv4 Address][github.com] Timed out.

**Comment by holmium** [comment]
这个，有时间解决，，，，，，

**Comment by litrue** [comment]
同样的问题，2.x好用吗？

**Comment by smovie** [comment]
2.x TCP timeout的几率要少很多

**Comment by wendellou** [comment]
感觉还没有解决

**Comment by holmium** [comment]
@wendellou 5版本不再更新
