### ISSUE TITLE
DomainStatistic域名统计启用后怎么看？

### ISSUE THREAD

**Issue by sunshineplan** [holmium/dnsforwarder#66]
不知道这个是什么东西，怎么个看法。

**Comment by holmium** [comment]
有个statistic.txt文件

**Comment by sunshineplan** [comment]
我是搭在ubuntu12.04上的，没有找到这个txt文件呢
不知道是不是和我用的不是root账户有关？

**Comment by holmium** [comment]
/root/.dnsforwarder/

**Comment by sunshineplan** [comment]
那我知道了，不过我是用的非root账户，启动命令为“sudo dnsforwarder -f '~/.dnsforwarder/config' -d”（我在当前用户home文件夹内建的.dnsforwarder文件夹和配置文件），是没有权限在/root/.dnsforwarder/读写的，所以就没有这个统计文件了。

**Comment by holmium** [comment]
你是怎么在没有root权限的状态开启53端口的？

**Comment by sunshineplan** [comment]
sudo可以的
