### ISSUE TITLE
不能与其它DNS软件进行级联

### ISSUE THREAD

**Issue by majiayeah** [holmium/dnsforwarder#70]
由于墙升高了，导致TCP模式查询DNS也会受到关键字检测而阻断，TCP查询模式不能很好的使用。
于是想到能否将dnsforwarder与其它加密的DNS软件进行级联。
设置如下：

windows 8.1系统

使用DNSCrypt加密连接到某公共DNS，监听本地的127.0.0.2，端口53，TCP与UDP均监听

如果直接将系统DNS设置到127.0.0.2，可正常使用。

然后，使用dnsforwarder优先UDP模式，TCP服务器设置127.0.0.2:53

发现dnsforwarder不能从127.0.0.2:53取到查询结果，此方法无法使用。

然后尝试让dnsforwarder从UDP的127.0.0.2:53查询，也无法成功。

后改成DNScrypt监听127.0.0.1:54，重复上述试验，dnsforwarder均不能正常查询到结果。

后又使用另一款软件，DNS2SOCKS，通过socks查询DNS，替代上面的DNScrypt，重复上述试验，dnsforwarder仍不能正常查询到结果。

请问这是什么问题？dnsforwarder无法与其它软件进行级联工作吗？有什么解决的办法吗？

**Comment by majiayeah** [comment]
补充一下，使用的是dnsforwarder的2.X版本。

**Comment by yyy8888** [comment]
改DNScrypt端口，配置入dnsforwarder

改DNScrypt端口 *.reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\dnscrypt-proxy\Parameters]
"LocalAddress"="127.0.0.100:53"

配置入dnsforwarder:
TCPServer 127.0.0.100

**Comment by yyy8888** [comment]
系统DNS设置到127.0.0.1
