### ISSUE TITLE
ubuntu 14.10无法编译安装dnsforwarder,急啊！

### ISSUE THREAD

**Issue by yuan78** [holmium/dnsforwarder#72]
ubuntu 14.10无法编译安装dnsforwarder，急啊！
已经解压所有文件（是最新版的DNSforwarder-5），但是make命令无法编译，用 ./configure报错说： configure: error: No libcurl found. （先用./configure 说权限不够，但是已经是sudo身份了啊，后来是用chmod改了configure 777的权限才能运行，但是还是报错）

大神啊，请告知正确的编译安装步骤啊（下载的是你最新的源码啊），但是就是搞不定无法安装啊？

一般不就是就是make& make install,为什么用make却又说找不到makefile文件，急啊！

**Comment by matthew728960** [comment]
需要安装libcurl，试试
sudo apt-get install libcurl

**Comment by yuan78** [comment]
好的，多谢！

2015-04-03 0:02 GMT+08:00 Matthew Sheppard <notifications@github.com>:
