### ISSUE TITLE
什么时候能修复5.x的版本tcp查询timeout问题

### ISSUE THREAD

**Issue by yyy8888** [holmium/dnsforwarder#73]
RT，另外能否加强Hosts支持，借鉴哈http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

**Comment by holmium** [comment]
tcp Timeout 问题真不是那么容易解决。
如果给Hosts加上正则表达式的支持，首先WindowsAPI似乎没有正则的API（有吗？我没找到过），Linux下倒是有，但是没法跨平台，如果用现有跨平台的库，那软件大小会增加，软件分发上就会有不方便的地方。当然如果你有更好的建议的话

**Comment by yfdyh000** [comment]
还没有用过本项目，但关于功能支持，https://github.com/chengr28/Pcap_DNSProxy 的代码也许可参考。

**Comment by yyy8888** [comment]
Pcap_DNSProxy 基于WinPcap。AcrylicHome也有代码可参考http://sourceforge.net/projects/acrylic/?source=typ_redirect

**Comment by LazyZhu** [comment]
借鉴下pdnsd/deadwood(maradns)的tcp查询部分?

**Comment by yyy8888** [comment]
class procedure THostsCache.ParseHostsLine(FileStreamLineData: String; HostsLineIndexA: Integer; HostsLineIndexB: Integer; HostsLineAddressData: Integer; var HostsCacheListLastAdded: String; var HostsCacheListNeedsSorting: Boolean);
var
  HostsLineTextData: String;
begin
  HostsLineTextData := Copy(FileStreamLineData, HostsLineIndexA, HostsLineIndexB - HostsLineIndexA);

  if (FileStreamLineData[HostsLineIndexA] = '-') then begin
    THostsCache_Exceptions.Add(Copy(HostsLineTextData, 2, MaxInt))
  end else if (FileStreamLineData[HostsLineIndexA] = '/') then begin
    THostsCache_Expressions.Add(Copy(HostsLineTextData, 2, MaxInt), TObject(HostsLineAddressData))
  end else if (FileStreamLineData[HostsLineIndexA] = '>') then begin
    HostsLineTextData := Copy(HostsLineTextData, 2, MaxInt);
    THostsCache_Patterns.AddObject('*.' + HostsLineTextData, TObject(HostsLineAddressData));
    THostsCache_List.AddObject(HostsLineTextData, TObject(HostsLineAddressData)); if (HostsLineTextData < HostsCacheListLastAdded) then HostsCacheListNeedsSorting := True; HostsCacheListLastAdded := HostsLineTextData;
  end else if (Pos('*', HostsLineTextData) > 0) or (Pos('?', HostsLineTextData) > 0) then begin
    THostsCache_Patterns.AddObject(HostsLineTextData, TObject(HostsLineAddressData))
  end else begin
    THostsCache_List.AddObject(HostsLineTextData, TObject(HostsLineAddressData)); if (HostsLineTextData < HostsCacheListLastAdded) then HostsCacheListNeedsSorting := True; HostsCacheListLastAdded := HostsLineTextData;
  end;
end;
