### ISSUE TITLE
mac安装时我make报错，哪位大哥帮看一下，小弟不胜感激！！！

### ISSUE THREAD

**Issue by ericyin521** [holmium/dnsforwarder#77]
make  all-am
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT addresschunk.o -MD -MP -MF .deps/addresschunk.Tpo -c -o addresschunk.o addresschunk.c
mv -f .deps/addresschunk.Tpo .deps/addresschunk.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT addresslist.o -MD -MP -MF .deps/addresslist.Tpo -c -o addresslist.o addresslist.c
mv -f .deps/addresslist.Tpo .deps/addresslist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT array.o -MD -MP -MF .deps/array.Tpo -c -o array.o array.c
mv -f .deps/array.Tpo .deps/array.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT bst.o -MD -MP -MF .deps/bst.Tpo -c -o bst.o bst.c
mv -f .deps/bst.Tpo .deps/bst.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT cacheht.o -MD -MP -MF .deps/cacheht.Tpo -c -o cacheht.o cacheht.c
mv -f .deps/cacheht.Tpo .deps/cacheht.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT debug.o -MD -MP -MF .deps/debug.Tpo -c -o debug.o debug.c
mv -f .deps/debug.Tpo .deps/debug.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT dnscache.o -MD -MP -MF .deps/dnscache.Tpo -c -o dnscache.o dnscache.c
mv -f .deps/dnscache.Tpo .deps/dnscache.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT dnsgenerator.o -MD -MP -MF .deps/dnsgenerator.Tpo -c -o dnsgenerator.o dnsgenerator.c
mv -f .deps/dnsgenerator.Tpo .deps/dnsgenerator.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT dnsparser.o -MD -MP -MF .deps/dnsparser.Tpo -c -o dnsparser.o dnsparser.c
mv -f .deps/dnsparser.Tpo .deps/dnsparser.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT dnsrelated.o -MD -MP -MF .deps/dnsrelated.Tpo -c -o dnsrelated.o dnsrelated.c
mv -f .deps/dnsrelated.Tpo .deps/dnsrelated.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT domainstatistic.o -MD -MP -MF .deps/domainstatistic.Tpo -c -o domainstatistic.o domainstatistic.c
domainstatistic.c: In function ‘DomainStatistic_Hold’:
domainstatistic.c:256: warning: passing argument 2 of ‘Array_Sort’ from incompatible pointer type
mv -f .deps/domainstatistic.Tpo .deps/domainstatistic.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT downloader.o -MD -MP -MF .deps/downloader.Tpo -c -o downloader.o downloader.c
mv -f .deps/downloader.Tpo .deps/downloader.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT excludedlist.o -MD -MP -MF .deps/excludedlist.Tpo -c -o excludedlist.o excludedlist.c
excludedlist.c: In function ‘LoadDisableType’:
excludedlist.c:79: warning: passing argument 4 of ‘Bst_Init’ from incompatible pointer type
mv -f .deps/excludedlist.Tpo .deps/excludedlist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT extendablebuffer.o -MD -MP -MF .deps/extendablebuffer.Tpo -c -o extendablebuffer.o extendablebuffer.c
mv -f .deps/extendablebuffer.Tpo .deps/extendablebuffer.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT gfwlist.o -MD -MP -MF .deps/gfwlist.Tpo -c -o gfwlist.o gfwlist.c
gfwlist.c: In function ‘GfwList_Match’:
gfwlist.c:291: warning: passing argument 1 of ‘MatchDomain’ discards qualifiers from pointer target type
mv -f .deps/gfwlist.Tpo .deps/gfwlist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT hosts.o -MD -MP -MF .deps/hosts.Tpo -c -o hosts.o hosts.c
hosts.c: In function ‘DynamicHosts_GetByQuestion’:
hosts.c:259: warning: passing argument 1 of ‘Hosts_GetFromContainer’ discards qualifiers from pointer target type
mv -f .deps/hosts.Tpo .deps/hosts.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT ipchunk.o -MD -MP -MF .deps/ipchunk.Tpo -c -o ipchunk.o ipchunk.c
mv -f .deps/ipchunk.Tpo .deps/ipchunk.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT querydnsbase.o -MD -MP -MF .deps/querydnsbase.Tpo -c -o querydnsbase.o querydnsbase.c
mv -f .deps/querydnsbase.Tpo .deps/querydnsbase.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT querydnsinterface.o -MD -MP -MF .deps/querydnsinterface.Tpo -c -o querydnsinterface.o querydnsinterface.c
mv -f .deps/querydnsinterface.Tpo .deps/querydnsinterface.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT querydnslistentcp.o -MD -MP -MF .deps/querydnslistentcp.Tpo -c -o querydnslistentcp.o querydnslistentcp.c
mv -f .deps/querydnslistentcp.Tpo .deps/querydnslistentcp.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT querydnslistenudp.o -MD -MP -MF .deps/querydnslistenudp.Tpo -c -o querydnslistenudp.o querydnslistenudp.c
mv -f .deps/querydnslistenudp.Tpo .deps/querydnslistenudp.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT readconfig.o -MD -MP -MF .deps/readconfig.Tpo -c -o readconfig.o readconfig.c
mv -f .deps/readconfig.Tpo .deps/readconfig.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT readline.o -MD -MP -MF .deps/readline.Tpo -c -o readline.o readline.c
mv -f .deps/readline.Tpo .deps/readline.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT request_response.o -MD -MP -MF .deps/request_response.Tpo -c -o request_response.o request_response.c
mv -f .deps/request_response.Tpo .deps/request_response.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT simpleht.o -MD -MP -MF .deps/simpleht.Tpo -c -o simpleht.o simpleht.c
mv -f .deps/simpleht.Tpo .deps/simpleht.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT statichosts.o -MD -MP -MF .deps/statichosts.Tpo -c -o statichosts.o statichosts.c
statichosts.c: In function ‘Hosts_LoadFromMetaLine’:
statichosts.c:276: warning: passing argument 1 of ‘GetKeyNameAndValue’ discards qualifiers from pointer target type
mv -f .deps/statichosts.Tpo .deps/statichosts.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT stringchunk.o -MD -MP -MF .deps/stringchunk.Tpo -c -o stringchunk.o stringchunk.c
mv -f .deps/stringchunk.Tpo .deps/stringchunk.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT stringlist.o -MD -MP -MF .deps/stringlist.Tpo -c -o stringlist.o stringlist.c
mv -f .deps/stringlist.Tpo .deps/stringlist.Po
gcc -DHAVE_CONFIG_H -I.     -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2  -MT utils.o -MD -MP -MF .deps/utils.Tpo -c -o utils.o utils.c
utils.c:111:2: warning: #warning Implement this
utils.c: In function ‘Base64Decode’:
utils.c:295: warning: ‘BIO_new’ is deprecated (declared at /usr/include/openssl/bio.h:581)
utils.c:295: warning: ‘BIO_f_base64’ is deprecated (declared at /usr/include/openssl/evp.h:647)
utils.c:302: warning: ‘BIO_new_mem_buf’ is deprecated (declared at /usr/include/openssl/bio.h:617)
utils.c:312: warning: ‘BIO_free_all’ is deprecated (declared at /usr/include/openssl/bio.h:596)
utils.c:317: warning: ‘BIO_push’ is deprecated (declared at /usr/include/openssl/bio.h:594)
utils.c:328: warning: ‘BIO_free_all’ is deprecated (declared at /usr/include/openssl/bio.h:596)
utils.c:334: warning: ‘BIO_read’ is deprecated (declared at /usr/include/openssl/bio.h:585)
utils.c:337: warning: ‘BIO_free_all’ is deprecated (declared at /usr/include/openssl/bio.h:596)
utils.c:346: warning: ‘BIO_free_all’ is deprecated (declared at /usr/include/openssl/bio.h:596)
mv -f .deps/utils.Tpo .deps/utils.Po
gcc  -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2   -pthread  -o dnsforwarder addresschunk.o addresslist.o array.o bst.o cacheht.o debug.o dnscache.o dnsgenerator.o dnsparser.o dnsrelated.o domainstatistic.o downloader.o excludedlist.o extendablebuffer.o gfwlist.o hosts.o ipchunk.o main.o querydnsbase.o querydnsinterface.o querydnslistentcp.o querydnslistenudp.o readconfig.o readline.o request_response.o simpleht.o statichosts.o stringchunk.o stringlist.o utils.o  -lcrypto -lcurl -lm -lm 
make install
 ./install-sh -c -d '/usr/local/bin'
  /usr/bin/install -c dnsforwarder '/usr/local/bin'
make[1]: Nothing to be done for `install-data-am'.

**Comment by QuChao** [comment]
mac 提供了 bin 啊

**Comment by alexwhen** [comment]
我编译了个最新的bin，正在等pull request
