### ISSUE TITLE
对最小化和代理支持的建议

### ISSUE THREAD

**Issue by StrollStars** [holmium/dnsforwarder#78]
1.建议增加最小化到通知区域的功能，这个也有人提到，希望能够尽早实现。
2.建议增加代理功能，包括UDP转发。之前看配置文件好像支持TCP，但是今天看了下没有相关设置内容了。

**Comment by alexwhen** [comment]
最小化有-d参数可用

**Comment by holmium** [comment]
有tcp啊

**Comment by StrollStars** [comment]
回楼上作者：下载的是2.7版本，dnsforwarder.config中没有提到代理选项。

**Comment by holmium** [comment]
2.7的没有
