### ISSUE TITLE
经验分享：不同域名指定DNS有加速功能

### ISSUE THREAD

**Issue by yyy8888** [holmium/dnsforwarder#79]
DNSForwarder对照Acrylic使用一些时了，DNSForwarder对DNS配置比Acrylic灵活得多，尤其不同域名可以指定DNS这一项。
比如www.baidu.com，Acrylic只能是靠10个DNS的延迟量判断最先返回的IP去访问的，我这经常解析到180段，奇慢无比，DNSForwarder中配置指定用onedns解析，多半得到220段，可以秒开。
讨论：试想不同区域除了划分墙内墙外，再细分（大陆南北？不同国家？）有没有好的配置方式？
期望：DNSForwarder Hosts兼容Acrylic库就更完美了

**Comment by holmium** [comment]
有，但是用的多了会被封
