### ISSUE TITLE
最近发现UDP也经常Timed out

### ISSUE THREAD

**Issue by yyy8888** [holmium/dnsforwarder#80]
下面的日志[bbs.ntrqq.net]和[aerozb.blog.163.com]前后几秒是现有解析后有Timed out，
按道理应该读取chach了吧。关键是Timed out时，网页肯定会卡顿，难道与网络有关？
请作者看看：
另问：UDP DNS配置数有限制么？

Apr 16 09:02:33 [U][127.0.0.1][IPv4 Address][bbs.ntrqq.net] : 108 bytes
   Canonical Name:bbs-ntrqq-net.cdn.smartgslb.com
   IPv4 Address:207.226.142.186
   IPv4 Address:103.242.111.8
Apr 16 09:02:34 [U][127.0.0.1][IPv4 Address][www.cnzz.com] : 46 bytes
   IPv4 Address:42.156.162.55
Apr 16 09:02:35 [U][127.0.0.1][IPv4 Address][aerozb.blog.163.com] : 83 bytes
   Canonical Name:blog.163.com
   IPv4 Address:115.238.126.133
   IPv4 Address:115.238.126.134
Apr 16 09:02:42 [U][127.0.0.1][IPv4 Address][aerozb.blog.163.com] Timed out.
Apr 16 09:02:42 [U][127.0.0.1][IPv4 Address][rs.sinajs.cn] Timed out.
Apr 16 09:02:42 [U][127.0.0.1][IPv4 Address][tjs.sjs.sinajs.cn] Timed out.
Apr 16 09:02:42 [U][127.0.0.1][IPv4 Address][tp4.sinaimg.cn] Timed out.
Apr 16 09:02:46 [U][127.0.0.1][IPv4 Address][vulfile.masterconn.qq.com] : 151 bytes
   IPv4 Address:101.227.131.109
   Name Server:ns-tel1.qq.com
   Name Server:ns-tel1.qq.com
Apr 16 09:02:46 [C][127.0.0.1][IPv4 Address][masterconn11.qq.com] : 53 bytes
   IPv4 Address:101.226.103.111
Apr 16 09:02:51 [U][127.0.0.1][IPv4 Address][bbs.ntrqq.net] Timed out.

**Comment by yyy8888** [comment]
附上设置
UDPServer 42.62.101.146,159.226.118.1,223.5.5.5,112.124.47.27,182.254.185.148,114.114.114.114,125.186.16.48,61.85.167.135,59.25.156.130,127.0.0.100,208.67.220.220:5353,151.236.20.236:5353,106.185.41.36:5353,8.8.4.4:53,208.67.220.220:443,151.236.20.236:443,106.185.41.36:443

**Comment by holmium** [comment]
在启用并发模式的情况下，UDP服务器设置过多确实会影响性能
2015-4-16 上午9:15于 "yyy8888" <notifications@github.com>写道：
