### ISSUE TITLE
请问DedicatedServer字段支持通配符吗？

### ISSUE THREAD

**Issue by testcaoy7** [holmium/dnsforwarder#87]
原版的配置文件没有写清楚，请问DedicatedServer是否支持通配符？

比如 DedicatedServer *.tmall.com 223.6.6.6

请问这条记录会字面匹配*号，还是将所有以tmall.com结尾的域名转交给223.6.6.6解析？

如果不支持，能添加支持吗？一条一条写域名实在太过于麻烦

**Comment by holmium** [comment]
支持

**Comment by testcaoy7** [comment]
心里一块石头落了地……
这下可以放弃TCP解析了，和谷歌相关的域名只要递交给HelloDNS即可
