### ISSUE TITLE
mac 编译不通过

### ISSUE THREAD

**Issue by alexwhen** [holmium/dnsforwarder#89]
Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc  -pthread  -DDOWNLOAD_LIBCURL  -DBASE64_DECODER_OPENSSL  -O2   -pthread  -o dnsforwarder addresschunk.o addresslist.o array.o bst.o cacheht.o debug.o dnscache.o dnsgenerator.o dnsparser.o dnsrelated.o domainstatistic.o downloader.o excludedlist.o extendablebuffer.o gfwlist.o hosts.o ipchunk.o main.o querydnsbase.o querydnsinterface.o querydnslistentcp.o querydnslistenudp.o readconfig.o readline.o request_response.o simpleht.o statichosts.o stringchunk.o stringlist.o utils.o internalsocket.o socketpool.o  -lcrypto -lcurl -lm -lm
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_CacheTtlCrtl_Add", referenced from:
      _DNSCache_Init in dnscache.o
  "_CacheTtlCrtl_Add_From_StringList", referenced from:
      _DNSCache_Init in dnscache.o
  "_CacheTtlCrtl_Get", referenced from:
      _DNSCache_AddItemsToCache in dnscache.o
  "_CacheTtlCrtl_Init", referenced from:
      _DNSCache_Init in dnscache.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [dnsforwarder] Error 1
make: *** [all] Error 2

**Comment by caidaoli** [comment]
同样发现这个问题，查了一下源码，makefile.am最后面加上 cachettlcrtl.h cachettlcrtl.c，就可以了。

**Comment by alexwhen** [comment]
修正了，提交pullquest了，感谢楼上

**Comment by holmium** [comment]
忘更新makefile了
