### ISSUE TITLE
mac 编译不通过

### ISSUE THREAD

**Issue by alexwhen** [holmium/dnsforwarder#95]
Undefined symbols for architecture x86_64:
  "_CheckIP_Add_From_String", referenced from:
      _InitCheckIPs in request_response.o
  "_CheckIP_Find", referenced from:
      _SendBack in request_response.o
  "_CheckIP_Init", referenced from:
      _InitCheckIPs in request_response.o
ld: symbol(s) not found for architecture x86_64

你更新后，我再编吧

**Comment by holmium** [comment]
这版还没好
