### ISSUE TITLE
配置文件中LocalInterface的问题

### ISSUE THREAD

**Issue by huxim** [holmium/dnsforwarder#99]
请问支持配置多个LocalInterface么？如果支持,那么格式是：
LocalInterface 127.0.0.1,0.0.0.0
还是:
LocalInterface 127.0.0.1
LocalInterface 0.0.0.0

**Comment by holmium** [comment]
不支持多个LocalInterface

**Comment by huxim** [comment]
如果想提供给局域网使用设置0.0.0.0可以么?
